/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Encuesta;

import java.awt.Color;
import java.awt.Component;
import java.awt.FontMetrics;
import java.awt.Insets;
import java.awt.event.FocusAdapter;
import java.awt.event.FocusEvent;
import java.awt.event.FocusListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseMotionAdapter;
import java.awt.event.MouseMotionListener;

import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import javax.swing.border.Border;

import Interfaz.Home;

/**
 *
 * @author usuario
 */
public class Formulario extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Formulario.class.getName());

    /**
     * Creates new form Formulario
     */
    public Formulario() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FondoPanel = new javax.swing.JPanel();
        BarraPanel = new javax.swing.JPanel();
        flexiaLabel = new javax.swing.JLabel();
        Exit2 = new javax.swing.JLabel();
        TituloLabel = new javax.swing.JLabel();
        NombreLabel = new javax.swing.JLabel();
        NombreField = new javax.swing.JTextField();
        EdadLabel = new javax.swing.JLabel();
        EdadField = new javax.swing.JTextField();
        GeneroLabel = new javax.swing.JLabel();
        GeneroComboBox = new javax.swing.JComboBox<>();
        DominanteLabel = new javax.swing.JLabel();
        ManoComboBox = new javax.swing.JComboBox<>();
        OcupacionLabel = new javax.swing.JLabel();
        OcupacionField = new javax.swing.JTextField();
        HorasLabel = new javax.swing.JLabel();
        HorasComboBox = new javax.swing.JComboBox<>();
        SepadorPanel1 = new Rounded.RoundedPanel();
        SintomasLabel = new javax.swing.JLabel();
        Ej1Label = new javax.swing.JLabel();
        Ej1_2Label = new javax.swing.JLabel();
        jComboBox01 = new javax.swing.JComboBox<>();
        Ej2Label = new javax.swing.JLabel();
        Ej2_2Label = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        Ej3Label = new javax.swing.JLabel();
        Ej3_2Label = new javax.swing.JLabel();
        jComboBox03 = new javax.swing.JComboBox<>();
        Ej4Label = new javax.swing.JLabel();
        Ej4_2Label = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        SeparadorPanel2 = new Rounded.RoundedPanel();
        Ej5Label = new javax.swing.JLabel();
        Ej5_2Label = new javax.swing.JLabel();
        jComboBox5 = new javax.swing.JComboBox<>();
        Ej6Label = new javax.swing.JLabel();
        Ej6_2Label = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox<>();
        HabitosLabel = new javax.swing.JLabel();
        Ej7Label = new javax.swing.JLabel();
        Ej7_2Label = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        Ej8Label = new javax.swing.JLabel();
        Ej8_2Label = new javax.swing.JLabel();
        Ej8_3Label = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        SeparadorPanel3 = new Rounded.RoundedPanel();
        Ej9Label = new javax.swing.JLabel();
        Ej9_2Label = new javax.swing.JLabel();
        jComboBox09 = new javax.swing.JComboBox<>();
        Ej10Label = new javax.swing.JLabel();
        Ej10_2Label = new javax.swing.JLabel();
        jComboBox010 = new javax.swing.JComboBox<>();
        EstadoLabel = new javax.swing.JLabel();
        Estado_2Label = new javax.swing.JLabel();
        Ej11Label = new javax.swing.JLabel();
        Ej11_2Label = new javax.swing.JLabel();
        NumerosLabel = new javax.swing.JLabel();
        jSlider10 = new javax.swing.JSlider();
        ButtonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        FondoPanel.setBackground(new java.awt.Color(250, 250, 250));
        FondoPanel.setAutoscrolls(true);
        FondoPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraPanel.setBackground(new java.awt.Color(30, 56, 136));
        BarraPanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        flexiaLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 24)); // NOI18N
        flexiaLabel.setForeground(new java.awt.Color(255, 255, 255));
        flexiaLabel.setText("ENCUESTA DIAGNOSTICA");
        BarraPanel.add(flexiaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        Exit2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        Exit2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit2MouseClicked(evt);
            }
        });
        BarraPanel.add(Exit2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 30, 40));

        FondoPanel.add(BarraPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 40));

        TituloLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 1, 36)); // NOI18N
        TituloLabel.setForeground(new java.awt.Color(51, 51, 51));
        TituloLabel.setText("Encuesta diagnostica inicial");
        FondoPanel.add(TituloLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 80, 510, 50));

        NombreLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        NombreLabel.setForeground(new java.awt.Color(51, 51, 51));
        NombreLabel.setText("Nombre completo: *");
        FondoPanel.add(NombreLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 154, 50));

        NombreField.setToolTipText("");
        NombreField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NombreFieldActionPerformed(evt);
            }
        });

        FondoPanel.add(NombreField, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 230, 40));

        EdadLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        EdadLabel.setForeground(new java.awt.Color(51, 51, 51));
        EdadLabel.setText("Edad: *");
        FondoPanel.add(EdadLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 90, 50));

        EdadField.setToolTipText("");
        FondoPanel.add(EdadField, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 120, 40));

        GeneroLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        GeneroLabel.setForeground(new java.awt.Color(51, 51, 51));
        GeneroLabel.setText("Genero:");
        FondoPanel.add(GeneroLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 90, 50));

        GeneroComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Femenino", "Masculino", "Prefiero no decirlo", " " }));
        FondoPanel.add(GeneroComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 450, 220, 40));

        DominanteLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        DominanteLabel.setForeground(new java.awt.Color(51, 51, 51));
        DominanteLabel.setText("Mano Dominante: *");
        FondoPanel.add(DominanteLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 500, 140, 50));

        ManoComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Derecha ", " Izquierda ", "Ambas", " " }));
        FondoPanel.add(ManoComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 550, 220, 40));

        OcupacionLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 16)); // NOI18N
        OcupacionLabel.setForeground(new java.awt.Color(51, 51, 51));
        OcupacionLabel.setText("Ocupación o actividad principal:*");
        FondoPanel.add(OcupacionLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 240, 50));
        FondoPanel.add(OcupacionField, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 660, 230, 40));

        HorasLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 16)); // NOI18N
        HorasLabel.setForeground(new java.awt.Color(51, 51, 51));
        HorasLabel.setText("Horas diarias frente al computador:");
        FondoPanel.add(HorasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 720, -1, 50));

        HorasComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Menos de 2 horas", "2 - 4 horas", "5 - 7 horas", "Más de 8 horas" }));
        HorasComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HorasComboBoxActionPerformed(evt);
            }
        });
        FondoPanel.add(HorasComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 770, 230, 40));

        SepadorPanel1.setBackground(new java.awt.Color(229, 229, 234));

        javax.swing.GroupLayout SepadorPanel1Layout = new javax.swing.GroupLayout(SepadorPanel1);
        SepadorPanel1.setLayout(SepadorPanel1Layout);
        SepadorPanel1Layout.setHorizontalGroup(
            SepadorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SepadorPanel1Layout.setVerticalGroup(
            SepadorPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        FondoPanel.add(SepadorPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, 10, 670));

        SintomasLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        SintomasLabel.setForeground(new java.awt.Color(51, 51, 51));
        SintomasLabel.setText("Sintomas actuales: *");
        FondoPanel.add(SintomasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 200, 170, 50));

        Ej1Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej1Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej1Label.setText("1. ¿Siente entumecimiento u hormigueo en");
        FondoPanel.add(Ej1Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 250, 320, 40));

        Ej1_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej1_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej1_2Label.setText(" los dedos (pulgar, índice, medio o anular)? *");
        FondoPanel.add(Ej1_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 290, 310, 30));

        jComboBox01.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre", " " }));
        jComboBox01.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox01ActionPerformed(evt);
            }
        });
        FondoPanel.add(jComboBox01, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, 220, 40));

        Ej2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej2Label.setText("2. ¿Ha sentido debilidad o pérdida de fuerza ");
        FondoPanel.add(Ej2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 390, 320, 40));

        Ej2_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej2_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej2_2Label.setText("al sujetar objetos? *");
        FondoPanel.add(Ej2_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 430, 320, 20));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre", " " }));
        FondoPanel.add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 220, 40));

        Ej3Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej3Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej3Label.setText("3. ¿Siente dolor intenso en la muñeca o el ");
        FondoPanel.add(Ej3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 520, 320, 40));

        Ej3_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej3_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej3_2Label.setText("antebrazo, durante el día ? *");
        FondoPanel.add(Ej3_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 560, 320, 30));

        jComboBox03.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre", " " }));
        FondoPanel.add(jComboBox03, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 610, 220, 40));

        Ej4Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej4Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej4Label.setText("4. ¿El dolor o entumecimiento se agrava al ");
        FondoPanel.add(Ej4Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 660, 320, 40));

        Ej4_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej4_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej4_2Label.setText("usar el teclado, el celular o el mouse? ");
        FondoPanel.add(Ej4_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 700, 320, 30));

        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre", " " }));
        FondoPanel.add(jComboBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 750, 220, 40));

        SeparadorPanel2.setBackground(new java.awt.Color(229, 229, 234));

        javax.swing.GroupLayout SeparadorPanel2Layout = new javax.swing.GroupLayout(SeparadorPanel2);
        SeparadorPanel2.setLayout(SeparadorPanel2Layout);
        SeparadorPanel2Layout.setHorizontalGroup(
            SeparadorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SeparadorPanel2Layout.setVerticalGroup(
            SeparadorPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 660, Short.MAX_VALUE)
        );

        FondoPanel.add(SeparadorPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 190, 10, 660));

        Ej5Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej5Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej5Label.setText("5. ¿Tiene dificultad para realizar tareas finas");
        FondoPanel.add(Ej5Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 200, 320, 40));

        Ej5_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej5_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej5_2Label.setText("(abotonar, escribir, agarrar cosas pequeñas)? *");
        FondoPanel.add(Ej5_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 320, 30));

        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre", " " }));
        FondoPanel.add(jComboBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 280, 220, 40));

        Ej6Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej6Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej6Label.setText("6. ¿El dolor o la incomodidad interfiere con ");
        FondoPanel.add(Ej6Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 330, 320, 40));

        Ej6_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej6_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej6_2Label.setText("su sueño? *");
        FondoPanel.add(Ej6_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 360, 320, 30));

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre", " " }));
        FondoPanel.add(jComboBox6, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 220, 40));

        HabitosLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        HabitosLabel.setForeground(new java.awt.Color(51, 51, 51));
        HabitosLabel.setText("Hábitos y prevención ");
        FondoPanel.add(HabitosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 450, 190, 50));

        Ej7Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej7Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej7Label.setText("7. ¿Suele realizar pausas o estiramientos ");
        FondoPanel.add(Ej7Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 500, 320, 40));

        Ej7_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej7_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej7_2Label.setText("durante su jornada laboral? *");
        FondoPanel.add(Ej7_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 530, 320, 40));

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre", " " }));
        FondoPanel.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 580, 220, 40));

        Ej8Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej8Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej8Label.setText("8. ¿Mantiene una postura ergonómica al");
        FondoPanel.add(Ej8Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 630, 320, 40));

        Ej8_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej8_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej8_2Label.setText("sentarse en el computador? (muñeca recta, ");
        FondoPanel.add(Ej8_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 660, 320, 30));

        Ej8_3Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej8_3Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej8_3Label.setText("teclado bajo, silla adecuada)? *");
        FondoPanel.add(Ej8_3Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 690, 320, 30));

        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre", " " }));
        FondoPanel.add(jComboBox8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 740, 220, 40));

        SeparadorPanel3.setBackground(new java.awt.Color(229, 229, 234));

        javax.swing.GroupLayout SeparadorPanel3Layout = new javax.swing.GroupLayout(SeparadorPanel3);
        SeparadorPanel3.setLayout(SeparadorPanel3Layout);
        SeparadorPanel3Layout.setHorizontalGroup(
            SeparadorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );
        SeparadorPanel3Layout.setVerticalGroup(
            SeparadorPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 670, Short.MAX_VALUE)
        );

        FondoPanel.add(SeparadorPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 180, 10, 670));

        Ej9Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej9Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej9Label.setText("9. ¿Utiliza algún tipo de soporte, férula ");
        FondoPanel.add(Ej9Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 200, 300, 40));

        Ej9_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej9_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej9_2Label.setText("o muñequera para aliviar molestias?");
        FondoPanel.add(Ej9_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 230, 300, 40));

        jComboBox09.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Si", "No", "A veces" }));
        FondoPanel.add(jComboBox09, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 280, 220, 40));

        Ej10Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej10Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej10Label.setText("10. ¿Siente alivio al sacudir la mano ");
        FondoPanel.add(Ej10Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 330, 300, 40));

        Ej10_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej10_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej10_2Label.setText("o estirarla? *");
        FondoPanel.add(Ej10_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 360, 300, 30));

        jComboBox010.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Si", "No", "A veces" }));
        FondoPanel.add(jComboBox010, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 400, 220, 40));

        EstadoLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        EstadoLabel.setForeground(new java.awt.Color(51, 51, 51));
        EstadoLabel.setText("Autoevaluación del estado ");
        FondoPanel.add(EstadoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 460, 280, 50));

        Estado_2Label.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        Estado_2Label.setForeground(new java.awt.Color(51, 51, 51));
        Estado_2Label.setText("actual ");
        FondoPanel.add(Estado_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 500, 260, 30));

        Ej11Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej11Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej11Label.setText("11. ¿Cómo describiría su nivel actual ");
        FondoPanel.add(Ej11Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 540, 300, 40));

        Ej11_2Label.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        Ej11_2Label.setForeground(new java.awt.Color(0, 0, 0));
        Ej11_2Label.setText("de dolor o molestia en la muñeca? *");
        FondoPanel.add(Ej11_2Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 570, 300, 40));

        NumerosLabel.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        NumerosLabel.setForeground(new java.awt.Color(51, 51, 51));
        NumerosLabel.setText("0 Ninguno — 10 Dolor intenso");
        FondoPanel.add(NumerosLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 630, 250, 30));

        jSlider10.setMajorTickSpacing(1);
        jSlider10.setMaximum(10);
        jSlider10.setMinimum(1);
        jSlider10.setPaintLabels(true);
        jSlider10.setPaintTicks(true);
        jSlider10.setValue(1);
        FondoPanel.add(jSlider10, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 680, 230, -1));

        ButtonEnviar.setBackground(new java.awt.Color(152, 206, 255));
        ButtonEnviar.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonEnviar.setText("Finalizar encuesta");
        ButtonEnviar.setToolTipText("");
        ButtonEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonEnviarMouseExited(evt);
            }
        });
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });
        FondoPanel.add(ButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 900, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FondoPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 982, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        // --- INICIO: Accesibilidad/asteriscos y borde azul para encuesta ---

        Color azulIntenso = new Color(0, 82, 204);
        Border bordeAzul = BorderFactory.createLineBorder(azulIntenso, 2);

        // Obtener bordes por defecto según tipo (seguro si alguno es null)
        Border bordeDefaultText = UIManager.getBorder("TextField.border") != null
                ? UIManager.getBorder("TextField.border")
                : BorderFactory.createLineBorder(Color.GRAY, 1);
        Border bordeDefaultCombo = UIManager.getBorder("ComboBox.border") != null
                ? UIManager.getBorder("ComboBox.border")
                : BorderFactory.createLineBorder(Color.GRAY, 1);

        // Labels obligatorios (incluyendo preguntas con *)
        JLabel[] labelsObligatorios = {
            NombreLabel, EdadLabel, GeneroLabel, DominanteLabel, OcupacionLabel, HorasLabel,
            Ej5_2Label, Ej6_2Label, Ej7_2Label, Ej8_3Label, Ej10_2Label, Ej11_2Label
        };

        // Componentes obligatorios correspondientes
        JComponent[] campos = {
            NombreField, EdadField, GeneroComboBox, ManoComboBox, OcupacionField, HorasComboBox,
            jComboBox5, jComboBox6, jComboBox7, jComboBox8, jComboBox010,
            (JComponent)jSlider10 // Slider → se valida diferente, pero se agrega aquí para foco/borde
        };

        // Creamos array de bordes por defecto correspondiente a cada campo
        Border[] bordesDefaultPorCampo = new Border[campos.length];
        for (int i = 0; i < campos.length; i++) {
            if (campos[i] instanceof javax.swing.JTextField) {
                bordesDefaultPorCampo[i] = bordeDefaultText;
            } else if (campos[i] instanceof javax.swing.JComboBox) {
                bordesDefaultPorCampo[i] = bordeDefaultCombo;
            } else {
                // fallback
                bordesDefaultPorCampo[i] = campos[i].getBorder() != null ? campos[i].getBorder() : bordeDefaultText;
            }
            // aseguramos que el componente tenga ese borde inicial
            campos[i].setBorder(bordesDefaultPorCampo[i]);
        }

        // Detector de hover puntual sobre el asterisco dentro del JLabel
        MouseMotionListener asteriskDetector = new MouseMotionAdapter() {
            @Override
            public void mouseMoved(MouseEvent e) {
                JLabel lbl = (JLabel) e.getSource();
                String text = lbl.getText();
                if (text == null || !text.contains("*")) {
                    lbl.setToolTipText(null);
                    return;
                }
                int idx = text.lastIndexOf('*');
                if (idx < 0) { lbl.setToolTipText(null); return; }

                String before = text.substring(0, idx).trim();
                FontMetrics fm = lbl.getFontMetrics(lbl.getFont());
                Insets inset = lbl.getInsets();
                int start = inset.left + fm.stringWidth(before);
                int end = start + fm.charWidth('*');
                int x = e.getX();
                int margin = 3;
                if (x >= start - margin && x <= end + margin) {
                    lbl.setToolTipText("Campo obligatorio");
                } else {
                    lbl.setToolTipText(null);
                }
            }
        };

        // Focus listener: pone borde azul solo mientras hay foco y restaura al perderlo
        FocusListener focusBorder = new FocusAdapter() {
            @Override
            public void focusGained(FocusEvent e) {
                Component c = e.getComponent();
                // encontrar índice del componente para usar su borde default al perder foco
                int idx = -1;
                for (int i = 0; i < campos.length; i++) if (campos[i] == c) { idx = i; break; }
                ((JComponent) c).setBorder(bordeAzul);
            }
            @Override
            public void focusLost(FocusEvent e) {
                Component c = e.getComponent();
                int idx = -1;
                for (int i = 0; i < campos.length; i++) if (campos[i] == c) { idx = i; break; }
                if (idx >= 0) {
                    ((JComponent) c).setBorder(bordesDefaultPorCampo[idx]);
                } else {
                    ((JComponent) c).setBorder(bordeDefaultText);
                }
            }
        };

        // Click en label → dar foco al campo correspondiente
        MouseAdapter clickLabel = new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
                Component src = e.getComponent();
                for (int i = 0; i < labelsObligatorios.length; i++) {
                    if (src == labelsObligatorios[i]) {
                        campos[i].requestFocusInWindow();
                        campos[i].setBorder(bordeAzul);
                        break;
                    }
                }
            }
        };

        // Asignar listeners a labels y campos
        for (int i = 0; i < labelsObligatorios.length; i++) {
            labelsObligatorios[i].addMouseMotionListener(asteriskDetector);
            labelsObligatorios[i].setFocusable(true); // accesibilidad teclado
            labelsObligatorios[i].addMouseListener(clickLabel);
        }

        for (int i = 0; i < campos.length; i++) {
            campos[i].addFocusListener(focusBorder);
            // también permitir click en el campo para forzar borde azul
            campos[i].addMouseListener(new MouseAdapter() {
                @Override public void mousePressed(MouseEvent e) {
                    ((JComponent)e.getComponent()).setBorder(bordeAzul);
                }
            });
        }

        // --- FIN: Accesibilidad/asteriscos y borde azul para encuesta ---


    }// </editor-fold>//GEN-END:initComponents

    private void guardarDatosEnBD() {

        // ✅ Validaciones básicas
        if (NombreField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Ingrese su nombre.");
            return;
        }
        if (OcupacionField.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "⚠️ Ingrese su ocupación.");
            return;
        }

        String edadTexto = EdadField.getText().trim();
        int edad;
        try {
            edad = Integer.parseInt(edadTexto);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "⚠️ Ingrese una edad válida.");
            return;
        }

        String genero = (String) GeneroComboBox.getSelectedItem();
        if (genero.equals("Seleccione una")) {
            JOptionPane.showMessageDialog(this, "⚠️ Seleccione un género.");
            return;
        }

        String mano = (String) ManoComboBox.getSelectedItem();
        if (mano.equals("Seleccione una")) {
            JOptionPane.showMessageDialog(this, "⚠️ Seleccione la mano dominante.");
            return;
        }

        String ocupacion = OcupacionField.getText();

        String horasTexto = (String) HorasComboBox.getSelectedItem();
        int horasComputador;
        switch (horasTexto) {
            case "Menos de 2 horas": horasComputador = 1; break;
            case "2 - 4 horas": horasComputador = 3; break;
            case "5 - 7 horas": horasComputador = 6; break;
            case "Más de 8 horas": horasComputador = 10; break;
            default:
                JOptionPane.showMessageDialog(this, "⚠️ Seleccione una opción válida en horas frente al computador.");
                return;
        }

        // ✅ Obtener opciones seleccionadas
        String sintoma1 = jComboBox01.getSelectedItem().toString();
        String sintoma2 = jComboBox2.getSelectedItem().toString();
        String sintoma3 = jComboBox03.getSelectedItem().toString();
        String sintoma4 = jComboBox4.getSelectedItem().toString();
        String sintoma5 = jComboBox5.getSelectedItem().toString();
        String sintoma6 = jComboBox6.getSelectedItem().toString();
        String habito1 = jComboBox7.getSelectedItem().toString();
        String habito2 = jComboBox8.getSelectedItem().toString();
        String prevencion1 = jComboBox09.getSelectedItem().toString();
        String prevencion2 = jComboBox010.getSelectedItem().toString();
        int nivelDolor = jSlider10.getValue();

        String sql = "INSERT INTO encuesta (nombre, edad, genero, mano_dominante, ocupacion, horas_computador, "
                + "sintoma1, sintoma2, sintoma3, sintoma4, sintoma5, sintoma6, habito1, habito2, "
                + "prevencion1, prevencion2, nivel_dolor) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)";

        try (java.sql.Connection conn = com.mycompany.flexia.database.Conexion.getConnection();
            java.sql.PreparedStatement ps = conn.prepareStatement(sql)) {

            ps.setString(1, NombreField.getText());
            ps.setInt(2, edad);
            ps.setString(3, genero);
            ps.setString(4, mano);
            ps.setString(5, ocupacion);
            ps.setInt(6, horasComputador);
            ps.setString(7, sintoma1);
            ps.setString(8, sintoma2);
            ps.setString(9, sintoma3);
            ps.setString(10, sintoma4);
            ps.setString(11, sintoma5);
            ps.setString(12, sintoma6);
            ps.setString(13, habito1);
            ps.setString(14, habito2);
            ps.setString(15, prevencion1);
            ps.setString(16, prevencion2);
            ps.setInt(17, nivelDolor);

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "✅ Encuesta almacenada correctamente 🎉");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "❌ Error al guardar datos:\n" + e.getMessage());
        }
    }


    private void Exit2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit2MouseClicked
        System.exit(0);
    }//GEN-LAST:event_Exit2MouseClicked

    private void HorasComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HorasComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HorasComboBoxActionPerformed

    private void jComboBox01ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox01ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox01ActionPerformed

    private void ButtonEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEnviarMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEnviarMouseEntered

    private void ButtonEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEnviarMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEnviarMouseExited

    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        guardarDatosEnBD(); // ✅ Primero guarda los datos
        Home home = new Home();
        home.setVisible(true);
        home.setLocationRelativeTo(null);
        dispose();
    }

    private void NombreFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NombreFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NombreFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Formulario().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraPanel;
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JLabel DominanteLabel;
    private javax.swing.JTextField EdadField;
    private javax.swing.JLabel EdadLabel;
    private javax.swing.JLabel Ej10Label;
    private javax.swing.JLabel Ej10_2Label;
    private javax.swing.JLabel Ej11Label;
    private javax.swing.JLabel Ej11_2Label;
    private javax.swing.JLabel Ej1Label;
    private javax.swing.JLabel Ej1_2Label;
    private javax.swing.JLabel Ej2Label;
    private javax.swing.JLabel Ej2_2Label;
    private javax.swing.JLabel Ej3Label;
    private javax.swing.JLabel Ej3_2Label;
    private javax.swing.JLabel Ej4Label;
    private javax.swing.JLabel Ej4_2Label;
    private javax.swing.JLabel Ej5Label;
    private javax.swing.JLabel Ej5_2Label;
    private javax.swing.JLabel Ej6Label;
    private javax.swing.JLabel Ej6_2Label;
    private javax.swing.JLabel Ej7Label;
    private javax.swing.JLabel Ej7_2Label;
    private javax.swing.JLabel Ej8Label;
    private javax.swing.JLabel Ej8_2Label;
    private javax.swing.JLabel Ej8_3Label;
    private javax.swing.JLabel Ej9Label;
    private javax.swing.JLabel Ej9_2Label;
    private javax.swing.JLabel EstadoLabel;
    private javax.swing.JLabel Estado_2Label;
    private javax.swing.JLabel Exit2;
    private javax.swing.JPanel FondoPanel;
    private javax.swing.JComboBox<String> GeneroComboBox;
    private javax.swing.JLabel GeneroLabel;
    private javax.swing.JLabel HabitosLabel;
    private javax.swing.JComboBox<String> HorasComboBox;
    private javax.swing.JLabel HorasLabel;
    private javax.swing.JComboBox<String> ManoComboBox;
    private javax.swing.JTextField NombreField;
    private javax.swing.JLabel NombreLabel;
    private javax.swing.JLabel NumerosLabel;
    private javax.swing.JTextField OcupacionField;
    private javax.swing.JLabel OcupacionLabel;
    private Rounded.RoundedPanel SepadorPanel1;
    private Rounded.RoundedPanel SeparadorPanel2;
    private Rounded.RoundedPanel SeparadorPanel3;
    private javax.swing.JLabel SintomasLabel;
    private javax.swing.JLabel TituloLabel;
    private javax.swing.JLabel flexiaLabel;
    private javax.swing.JComboBox<String> jComboBox01;
    private javax.swing.JComboBox<String> jComboBox010;
    private javax.swing.JComboBox<String> jComboBox03;
    private javax.swing.JComboBox<String> jComboBox09;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JSlider jSlider10;
    // End of variables declaration//GEN-END:variables
}
