/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front_End;

/**
 *
 * @author usuario
 */
public class Encuesta1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Encuesta1.class.getName());

    // Para mover la ventana (barra superior)
    int xmouse, ymouse;

    /**
     * Creates new form Encuesta1
     */
    public Encuesta1() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Principal = new javax.swing.JPanel();
        jLabel_Titulo = new javax.swing.JLabel();
        jLabel_descripción = new javax.swing.JLabel();
        ImagenCarpianin = new javax.swing.JLabel();
        barra = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Panel_Datos = new javax.swing.JPanel();
        jLabel_icono1 = new javax.swing.JLabel();
        jLabel_Datos = new javax.swing.JLabel();
        jLabel_Nombre = new javax.swing.JLabel();
        jTextField_Nombre = new javax.swing.JTextField();
        jLabel_Edad = new javax.swing.JLabel();
        jTextField_Edad = new javax.swing.JTextField();
        jLabel_Mano = new javax.swing.JLabel();
        jLabel_Icono2 = new javax.swing.JLabel();
        jButton_Izq = new javax.swing.JButton();
        jButton_Der = new javax.swing.JButton();
        jLabel_Ocupacion = new javax.swing.JLabel();
        jTextField_Ocupacion = new javax.swing.JTextField();
        jLabel_Horas = new javax.swing.JLabel();
        jComboBox_Horas = new javax.swing.JComboBox<>();
        Panel_sintomas = new javax.swing.JPanel();
        jLabel_icono3 = new javax.swing.JLabel();
        jLabel_Sintomas = new javax.swing.JLabel();
        jLabel_icono4 = new javax.swing.JLabel();
        jLabel_Punto1_1 = new javax.swing.JLabel();
        jLabel_Punto1_2 = new javax.swing.JLabel();
        jComboBox_Punto1 = new javax.swing.JComboBox<>();
        jLabel_Punto2_1 = new javax.swing.JLabel();
        jLabel_Punto2_2 = new javax.swing.JLabel();
        jComboBox_Punto2 = new javax.swing.JComboBox<>();
        jLabel_Punto3_1 = new javax.swing.JLabel();
        jLabel_Punto3_2 = new javax.swing.JLabel();
        jComboBox_Punto3 = new javax.swing.JComboBox<>();
        jLabel_Punto4_1 = new javax.swing.JLabel();
        jLabel_Punto4_2 = new javax.swing.JLabel();
        jComboBox_Punto4 = new javax.swing.JComboBox<>();
        Panel_sintomas2 = new javax.swing.JPanel();
        jLabel_Punto5_1 = new javax.swing.JLabel();
        jLabel_Punto5_2 = new javax.swing.JLabel();
        jComboBox_Punto5 = new javax.swing.JComboBox<>();
        jLabel_Punto6_1 = new javax.swing.JLabel();
        jLabel_Punto6_2 = new javax.swing.JLabel();
        jComboBox_Punto6 = new javax.swing.JComboBox<>();
        Panel_habitos = new javax.swing.JPanel();
        jLabel_icono5 = new javax.swing.JLabel();
        jLabel_habitos = new javax.swing.JLabel();
        jLabel_Icono6 = new javax.swing.JLabel();
        jLabel_Punto7_1 = new javax.swing.JLabel();
        jLabel_Punto7_2 = new javax.swing.JLabel();
        jComboBox_punto7 = new javax.swing.JComboBox<>();
        jLabel_Punto8_1 = new javax.swing.JLabel();
        jLabel_Punto8_2 = new javax.swing.JLabel();
        jLabel_Punto8_3 = new javax.swing.JLabel();
        jComboBox_punto8 = new javax.swing.JComboBox<>();
        Panel_habitos2 = new javax.swing.JPanel();
        jLabel_Punto9_1 = new javax.swing.JLabel();
        jLabel_Punto9_2 = new javax.swing.JLabel();
        jComboBox_punto9 = new javax.swing.JComboBox<>();
        jLabel_Punto10_1 = new javax.swing.JLabel();
        jLabel_Punto10_2 = new javax.swing.JLabel();
        jComboBox_punto10 = new javax.swing.JComboBox<>();
        jPanel_Autoevaluacion = new javax.swing.JPanel();
        jLabel_Icono7 = new javax.swing.JLabel();
        jLabel_Auto = new javax.swing.JLabel();
        jLabel_Icono8 = new javax.swing.JLabel();
        jLabel_Punto11_1 = new javax.swing.JLabel();
        jLabel_Punto11_2 = new javax.swing.JLabel();
        jLabel_Punto11_3 = new javax.swing.JLabel();
        jSlider_nivel = new javax.swing.JSlider();
        BotonEnviar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel_Principal.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Principal.setMinimumSize(new java.awt.Dimension(1440, 1024));
        jPanel_Principal.setPreferredSize(new java.awt.Dimension(1440, 1024));
        jPanel_Principal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Titulo.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 36)); // NOI18N
        jLabel_Titulo.setForeground(new java.awt.Color(30, 56, 136));
        jLabel_Titulo.setText("Encuesta diagnostica inicial");
        jPanel_Principal.add(jLabel_Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 60, 510, 70));
        jLabel_Titulo.getAccessibleContext().setAccessibleDescription("Titulo del formulario");

        jLabel_descripción.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 20)); // NOI18N
        jLabel_descripción.setForeground(new java.awt.Color(153, 153, 153));
        jLabel_descripción.setText("Esta encuesta nos ayuda analizar tu caso y generar un pre-diagnostico");
        jPanel_Principal.add(jLabel_descripción, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 100, 680, 60));

        ImagenCarpianin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Carpianin.png"))); // NOI18N
        jPanel_Principal.add(ImagenCarpianin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1230, 730, 200, 270));
        ImagenCarpianin.getAccessibleContext().setAccessibleName("Imagen de Carpianin");

        barra.setBackground(new java.awt.Color(30, 56, 136));
        barra.setPreferredSize(new java.awt.Dimension(1440, 40));
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("FLEX-IA");
        barra.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        // Botón minimizar (estilo login)
        minimizebtn = new javax.swing.JPanel();
        minimizetxt = new javax.swing.JLabel();
        minimizebtn.setBackground(new java.awt.Color(30, 56, 136));
        minimizebtn.setLayout(new java.awt.BorderLayout());
        minimizetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizetxt.setText("-");
        minimizetxt.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 30));
        minimizetxt.setForeground(new java.awt.Color(250, 250, 250));
        minimizetxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizetxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizetxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizetxtMouseExited(evt);
            }
        });
        minimizebtn.add(minimizetxt, java.awt.BorderLayout.CENTER);
        barra.add(minimizebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 0, 60, 40));

        // Botón cerrar (reutiliza Exit como label)
        Closebtn = new javax.swing.JPanel();
        Closebtn.setBackground(new java.awt.Color(30, 56, 136));
        Closebtn.setLayout(new java.awt.BorderLayout());

        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });

        Closebtn.add(Exit, java.awt.BorderLayout.CENTER);
        barra.add(Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 0, 60, 40));
        Exit.getAccessibleContext().setAccessibleName("Salir de la app");

        jPanel_Principal.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Panel_Datos.setBackground(new java.awt.Color(255, 255, 255));
        Panel_Datos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Panel_Datos.setForeground(new java.awt.Color(0, 0, 0));
        Panel_Datos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_icono1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/usuario3.png"))); // NOI18N
        Panel_Datos.add(jLabel_icono1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));
        jLabel_icono1.getAccessibleContext().setAccessibleName("icono de datos personales");

        jLabel_Datos.setBackground(new java.awt.Color(30, 56, 136));
        jLabel_Datos.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 22)); // NOI18N
        jLabel_Datos.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Datos.setText("Datos personales");
        Panel_Datos.add(jLabel_Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 170, 40));

        jLabel_Nombre.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        jLabel_Nombre.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Nombre.setText("Nombre completo: *");
        Panel_Datos.add(jLabel_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 190, 20));

        jTextField_Nombre.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Nombre.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        Panel_Datos.add(jTextField_Nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 260, 40));
        jTextField_Nombre.getAccessibleContext().setAccessibleName("Campo de texto");

        jLabel_Edad.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        jLabel_Edad.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Edad.setText("Edad: *");
        Panel_Datos.add(jLabel_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 60, 40));

        jTextField_Edad.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Edad.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        Panel_Datos.add(jTextField_Edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 170, 40));
        jTextField_Edad.getAccessibleContext().setAccessibleName("Campo de texto");

        jLabel_Mano.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        jLabel_Mano.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Mano.setText("Mano Dominante: *");
        Panel_Datos.add(jLabel_Mano, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 180, 40));

        jLabel_Icono2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manos-abiertas.png"))); // NOI18N
        Panel_Datos.add(jLabel_Icono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 70, 80));
        jLabel_Icono2.getAccessibleContext().setAccessibleName("icono de mano dominante");

        jButton_Izq.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Izq.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jButton_Izq.setText("Izquierda");
        jButton_Izq.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/apuntando-a-la-izquierda.png"))); // NOI18N
        Panel_Datos.add(jButton_Izq, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 130, 40));

        jButton_Der.setBackground(new java.awt.Color(255, 255, 255));
        jButton_Der.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jButton_Der.setText("Derecha");
        jButton_Der.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/apuntando-a-la-derecha.png"))); // NOI18N
        Panel_Datos.add(jButton_Der, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 370, 140, 40));

        jLabel_Ocupacion.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 18)); // NOI18N
        jLabel_Ocupacion.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Ocupacion.setText("Ocupación o actividad principal:*");
        Panel_Datos.add(jLabel_Ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, 300, 40));

        jTextField_Ocupacion.setBackground(new java.awt.Color(255, 255, 255));
        jTextField_Ocupacion.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        Panel_Datos.add(jTextField_Ocupacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 500, 270, 40));
        jTextField_Ocupacion.getAccessibleContext().setAccessibleName("Campo de texto");

        jLabel_Horas.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 17)); // NOI18N
        jLabel_Horas.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Horas.setText("Horas diarias frente al computador:");
        Panel_Datos.add(jLabel_Horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 560, 300, 40));

        jComboBox_Horas.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Horas.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_Horas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Menos de 2 horas", " 2 - 4 horas", "5 - 7 horas", "Más de 8 horas" }));
        jComboBox_Horas.setToolTipText("");
        Panel_Datos.add(jComboBox_Horas, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 620, 260, 30));
        jComboBox_Horas.getAccessibleContext().setAccessibleName("opciones");

        jPanel_Principal.add(Panel_Datos, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 330, 730));

        Panel_sintomas.setBackground(new java.awt.Color(255, 255, 255));
        Panel_sintomas.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Panel_sintomas.setForeground(new java.awt.Color(0, 0, 0));
        Panel_sintomas.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_icono3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/sintoma.png"))); // NOI18N
        Panel_sintomas.add(jLabel_icono3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 40, 40));
        jLabel_icono3.getAccessibleContext().setAccessibleName("Icono de Sintomas actuales");

        jLabel_Sintomas.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 22)); // NOI18N
        jLabel_Sintomas.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Sintomas.setText("Sintomas actuales: ");
        Panel_sintomas.add(jLabel_Sintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 20, 210, 40));

        jLabel_icono4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/enfermedad.png"))); // NOI18N
        Panel_sintomas.add(jLabel_icono4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, 80));
        jLabel_icono4.getAccessibleContext().setAccessibleName("imagen de manos");

        jLabel_Punto1_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto1_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto1_1.setText("1. ¿Siente entumecimiento u hormigueo en");
        Panel_sintomas.add(jLabel_Punto1_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 330, 20));

        jLabel_Punto1_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto1_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto1_2.setText("los dedos (pulgar, índice, medio o anular)? *");
        Panel_sintomas.add(jLabel_Punto1_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 330, 20));

        jComboBox_Punto1.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Punto1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_Punto1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre" }));
        jComboBox_Punto1.setToolTipText("");
        Panel_sintomas.add(jComboBox_Punto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 260, 30));
        jComboBox_Punto1.getAccessibleContext().setAccessibleName("opciones");

        jLabel_Punto2_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto2_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto2_1.setText("2. ¿Ha sentido debilidad o pérdida de fuerza");
        Panel_sintomas.add(jLabel_Punto2_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 330, 20));

        jLabel_Punto2_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto2_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto2_2.setText("al sujetar objetos? *");
        Panel_sintomas.add(jLabel_Punto2_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 330, 20));

        jComboBox_Punto2.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Punto2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_Punto2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre" }));
        jComboBox_Punto2.setToolTipText("");
        Panel_sintomas.add(jComboBox_Punto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, 260, 30));
        jComboBox_Punto2.getAccessibleContext().setAccessibleName("opciones");

        jLabel_Punto3_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto3_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto3_1.setText("3. ¿Siente dolor intenso en la muñeca o el");
        Panel_sintomas.add(jLabel_Punto3_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 400, 330, 20));

        jLabel_Punto3_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto3_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto3_2.setText("antebrazo, durante el día ? *");
        Panel_sintomas.add(jLabel_Punto3_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 330, 20));

        jComboBox_Punto3.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Punto3.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_Punto3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre" }));
        jComboBox_Punto3.setToolTipText("");
        Panel_sintomas.add(jComboBox_Punto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 470, 260, 30));
        jComboBox_Punto3.getAccessibleContext().setAccessibleName("opciones");

        jLabel_Punto4_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto4_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto4_1.setText("4. ¿El dolor o entumecimiento se agrava al");
        Panel_sintomas.add(jLabel_Punto4_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, 330, 20));

        jLabel_Punto4_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto4_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto4_2.setText("usar el teclado, el celular o el mouse?");
        Panel_sintomas.add(jLabel_Punto4_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 570, 330, 20));

        jComboBox_Punto4.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Punto4.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_Punto4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre" }));
        jComboBox_Punto4.setToolTipText("");
        Panel_sintomas.add(jComboBox_Punto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 620, 260, 30));
        jComboBox_Punto4.getAccessibleContext().setAccessibleName("opciones");

        jPanel_Principal.add(Panel_sintomas, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, 370, 730));

        Panel_sintomas2.setBackground(new java.awt.Color(255, 255, 255));
        Panel_sintomas2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Panel_sintomas2.setForeground(new java.awt.Color(0, 0, 0));
        Panel_sintomas2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Punto5_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto5_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto5_1.setText("5. ¿Tiene dificultad para realizar tareas finas");
        Panel_sintomas2.add(jLabel_Punto5_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 340, 20));

        jLabel_Punto5_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto5_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto5_2.setText("(abotonar, escribir, agarrar cosas pequeñas)?*");
        Panel_sintomas2.add(jLabel_Punto5_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jComboBox_Punto5.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Punto5.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_Punto5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre" }));
        jComboBox_Punto5.setToolTipText("");
        Panel_sintomas2.add(jComboBox_Punto5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 90, 260, 30));
        jComboBox_Punto5.getAccessibleContext().setAccessibleName("opciones");

        jLabel_Punto6_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto6_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto6_1.setText("6. ¿El dolor o la incomodidad interfiere con");
        Panel_sintomas2.add(jLabel_Punto6_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 340, 20));

        jLabel_Punto6_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto6_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto6_2.setText("su sueño? *");
        Panel_sintomas2.add(jLabel_Punto6_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 380, 20));

        jComboBox_Punto6.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_Punto6.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_Punto6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre" }));
        jComboBox_Punto6.setToolTipText("");
        Panel_sintomas2.add(jComboBox_Punto6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 260, 30));
        jComboBox_Punto6.getAccessibleContext().setAccessibleName("opciones");

        jPanel_Principal.add(Panel_sintomas2, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, 360, 250));

        Panel_habitos.setBackground(new java.awt.Color(255, 255, 255));
        Panel_habitos.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Panel_habitos.setForeground(new java.awt.Color(0, 0, 0));
        Panel_habitos.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_icono5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salud.png"))); // NOI18N
        Panel_habitos.add(jLabel_icono5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 40, 40));
        jLabel_icono5.getAccessibleContext().setAccessibleName("icono de habitos");

        jLabel_habitos.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 22)); // NOI18N
        jLabel_habitos.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_habitos.setText("Hábitos y prevención");
        Panel_habitos.add(jLabel_habitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 210, 50));

        jLabel_Icono6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/manoss.png"))); // NOI18N
        Panel_habitos.add(jLabel_Icono6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 80, 70));
        jLabel_Icono6.getAccessibleContext().setAccessibleName("imagen de unas manos ");

        jLabel_Punto7_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto7_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto7_1.setText("7. ¿Suele realizar pausas o estiramientos ");
        Panel_habitos.add(jLabel_Punto7_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 340, 30));

        jLabel_Punto7_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto7_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto7_2.setText("durante su jornada laboral? *");
        Panel_habitos.add(jLabel_Punto7_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, 240, 30));

        jComboBox_punto7.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_punto7.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_punto7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre" }));
        jComboBox_punto7.setToolTipText("");
        Panel_habitos.add(jComboBox_punto7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 260, 30));
        jComboBox_punto7.getAccessibleContext().setAccessibleName("opciones");

        jLabel_Punto8_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto8_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto8_1.setText("8. ¿Mantiene una postura ergonómica al");
        Panel_habitos.add(jLabel_Punto8_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 340, 30));

        jLabel_Punto8_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto8_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto8_2.setText("sentarse en el computador? (muñeca recta,");
        Panel_habitos.add(jLabel_Punto8_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 330, 30));

        jLabel_Punto8_3.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto8_3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto8_3.setText("teclado bajo, silla adecuada)? *");
        Panel_habitos.add(jLabel_Punto8_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 330, 30));

        jComboBox_punto8.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_punto8.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_punto8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Nunca", "Rara vez", "A veces", "Frecuentemente", "Siempre" }));
        jComboBox_punto8.setToolTipText("");
        Panel_habitos.add(jComboBox_punto8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, 260, 30));
        jComboBox_punto8.getAccessibleContext().setAccessibleName("opciones");

        jPanel_Principal.add(Panel_habitos, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 430, 360, 470));

        Panel_habitos2.setBackground(new java.awt.Color(255, 255, 255));
        Panel_habitos2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        Panel_habitos2.setForeground(new java.awt.Color(0, 0, 0));
        Panel_habitos2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Punto9_1.setFont(new java.awt.Font("Epunda Slab", 0, 17)); // NOI18N
        jLabel_Punto9_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto9_1.setText("9. ¿Utiliza algún tipo de soporte, férula");
        Panel_habitos2.add(jLabel_Punto9_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 270, 20));

        jLabel_Punto9_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto9_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto9_2.setText("o muñequera para aliviar molestias?");
        Panel_habitos2.add(jLabel_Punto9_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 20));

        jComboBox_punto9.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_punto9.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_punto9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Si", "No", "A veces" }));
        jComboBox_punto9.setToolTipText("");
        Panel_habitos2.add(jComboBox_punto9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 260, 30));
        jComboBox_punto9.getAccessibleContext().setAccessibleName("opciones");

        jLabel_Punto10_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto10_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto10_1.setText("10. ¿Siente alivio al sacudir la mano ");
        Panel_habitos2.add(jLabel_Punto10_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 280, 20));

        jLabel_Punto10_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto10_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto10_2.setText("o estirarla? *");
        Panel_habitos2.add(jLabel_Punto10_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, 200, 20));

        jComboBox_punto10.setBackground(new java.awt.Color(255, 255, 255));
        jComboBox_punto10.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jComboBox_punto10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione una", "Si", "No", "A veces" }));
        jComboBox_punto10.setToolTipText("");
        Panel_habitos2.add(jComboBox_punto10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 260, 30));
        jComboBox_punto10.getAccessibleContext().setAccessibleName("opciones");

        jPanel_Principal.add(Panel_habitos2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 170, 300, 250));

        jPanel_Autoevaluacion.setBackground(new java.awt.Color(255, 255, 255));
        jPanel_Autoevaluacion.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(204, 204, 204), 2, true));
        jPanel_Autoevaluacion.setForeground(new java.awt.Color(0, 0, 0));
        jPanel_Autoevaluacion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel_Icono7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/salud2.png"))); // NOI18N
        jPanel_Autoevaluacion.add(jLabel_Icono7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 40, 40));

        jLabel_Auto.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 22)); // NOI18N
        jLabel_Auto.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_Auto.setText("Autoevaluación ");
        jPanel_Autoevaluacion.add(jLabel_Auto, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 190, 40));

        jLabel_Icono8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/autoeval.png"))); // NOI18N
        jPanel_Autoevaluacion.add(jLabel_Icono8, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 80, 70));

        jLabel_Punto11_1.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto11_1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto11_1.setText("11. ¿Cómo describiría su nivel actual");
        jPanel_Autoevaluacion.add(jLabel_Punto11_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 280, 30));

        jLabel_Punto11_2.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto11_2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto11_2.setText("de dolor o molestia en la muñeca? *");
        jPanel_Autoevaluacion.add(jLabel_Punto11_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 280, 30));

        jLabel_Punto11_3.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        jLabel_Punto11_3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel_Punto11_3.setText("0 = Sin dolor | 10 = Dolor maximo");
        jPanel_Autoevaluacion.add(jLabel_Punto11_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 260, 30));

        jSlider_nivel.setBackground(new java.awt.Color(255, 255, 255));
        jSlider_nivel.setFont(new java.awt.Font("Epunda Slab", 0, 14)); // NOI18N
        jSlider_nivel.setForeground(new java.awt.Color(0, 0, 0));
        jSlider_nivel.setMajorTickSpacing(1);
        jSlider_nivel.setMaximum(10);
        jSlider_nivel.setMinimum(1);
        jSlider_nivel.setPaintLabels(true);
        jSlider_nivel.setPaintTicks(true);
        jSlider_nivel.setValue(1);
        jPanel_Autoevaluacion.add(jSlider_nivel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 260, 60));
        jSlider_nivel.getAccessibleContext().setAccessibleName("opciones 1 al 10");

        jPanel_Principal.add(jPanel_Autoevaluacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 430, 300, 470));

        BotonEnviar.setBackground(new java.awt.Color(152, 206, 255));
        BotonEnviar.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        BotonEnviar.setForeground(new java.awt.Color(0, 0, 0));
        BotonEnviar.setText("Finalizar encuesta");
        jPanel_Principal.add(BotonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 930, 260, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel_Principal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel_Principal.getAccessibleContext().setAccessibleName("Ventana Encuesta diagnostica inicial");

        getAccessibleContext().setAccessibleName("Ventana Encuesta Diagnostica");
        getAccessibleContext().setAccessibleDescription("Es un formulario inicial para la app de escritorio Flexia");
        getAccessibleContext().setAccessibleParent(jPanel_Principal);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void barraMousePressed(java.awt.event.MouseEvent evt) {
        xmouse = evt.getX();
        ymouse = evt.getY();
    }

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {
        Closebtn.setBackground(java.awt.Color.red);
    }

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {
        Closebtn.setBackground(new java.awt.Color(30, 56, 136));
    }

    private void minimizetxtMouseEntered(java.awt.event.MouseEvent evt) {
        minimizebtn.setBackground(java.awt.Color.decode("#2e4ca9"));
    }

    private void minimizetxtMouseExited(java.awt.event.MouseEvent evt) {
        minimizebtn.setBackground(new java.awt.Color(30, 56, 136));
    }

    private void minimizetxtMouseClicked(java.awt.event.MouseEvent evt) {
        this.setState(javax.swing.JFrame.ICONIFIED);
    }

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        dispose();
    }//GEN-LAST:event_ExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Encuesta1().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonEnviar;
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel Closebtn;
    private javax.swing.JPanel minimizebtn;
    private javax.swing.JLabel minimizetxt;
    private javax.swing.JLabel ImagenCarpianin;
    private javax.swing.JPanel Panel_Datos;
    private javax.swing.JPanel Panel_habitos;
    private javax.swing.JPanel Panel_habitos2;
    private javax.swing.JPanel Panel_sintomas;
    private javax.swing.JPanel Panel_sintomas2;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel barra;
    private javax.swing.JButton jButton_Der;
    private javax.swing.JButton jButton_Izq;
    private javax.swing.JComboBox<String> jComboBox_Horas;
    private javax.swing.JComboBox<String> jComboBox_Punto1;
    private javax.swing.JComboBox<String> jComboBox_Punto2;
    private javax.swing.JComboBox<String> jComboBox_Punto3;
    private javax.swing.JComboBox<String> jComboBox_Punto4;
    private javax.swing.JComboBox<String> jComboBox_Punto5;
    private javax.swing.JComboBox<String> jComboBox_Punto6;
    private javax.swing.JComboBox<String> jComboBox_punto10;
    private javax.swing.JComboBox<String> jComboBox_punto7;
    private javax.swing.JComboBox<String> jComboBox_punto8;
    private javax.swing.JComboBox<String> jComboBox_punto9;
    private javax.swing.JLabel jLabel_Auto;
    private javax.swing.JLabel jLabel_Datos;
    private javax.swing.JLabel jLabel_Edad;
    private javax.swing.JLabel jLabel_Horas;
    private javax.swing.JLabel jLabel_Icono2;
    private javax.swing.JLabel jLabel_Icono6;
    private javax.swing.JLabel jLabel_Icono7;
    private javax.swing.JLabel jLabel_Icono8;
    private javax.swing.JLabel jLabel_Mano;
    private javax.swing.JLabel jLabel_Nombre;
    private javax.swing.JLabel jLabel_Ocupacion;
    private javax.swing.JLabel jLabel_Punto10_1;
    private javax.swing.JLabel jLabel_Punto10_2;
    private javax.swing.JLabel jLabel_Punto11_1;
    private javax.swing.JLabel jLabel_Punto11_2;
    private javax.swing.JLabel jLabel_Punto11_3;
    private javax.swing.JLabel jLabel_Punto1_1;
    private javax.swing.JLabel jLabel_Punto1_2;
    private javax.swing.JLabel jLabel_Punto2_1;
    private javax.swing.JLabel jLabel_Punto2_2;
    private javax.swing.JLabel jLabel_Punto3_1;
    private javax.swing.JLabel jLabel_Punto3_2;
    private javax.swing.JLabel jLabel_Punto4_1;
    private javax.swing.JLabel jLabel_Punto4_2;
    private javax.swing.JLabel jLabel_Punto5_1;
    private javax.swing.JLabel jLabel_Punto5_2;
    private javax.swing.JLabel jLabel_Punto6_1;
    private javax.swing.JLabel jLabel_Punto6_2;
    private javax.swing.JLabel jLabel_Punto7_1;
    private javax.swing.JLabel jLabel_Punto7_2;
    private javax.swing.JLabel jLabel_Punto8_1;
    private javax.swing.JLabel jLabel_Punto8_2;
    private javax.swing.JLabel jLabel_Punto8_3;
    private javax.swing.JLabel jLabel_Punto9_1;
    private javax.swing.JLabel jLabel_Punto9_2;
    private javax.swing.JLabel jLabel_Sintomas;
    private javax.swing.JLabel jLabel_Titulo;
    private javax.swing.JLabel jLabel_descripción;
    private javax.swing.JLabel jLabel_habitos;
    private javax.swing.JLabel jLabel_icono1;
    private javax.swing.JLabel jLabel_icono3;
    private javax.swing.JLabel jLabel_icono4;
    private javax.swing.JLabel jLabel_icono5;
    private javax.swing.JPanel jPanel_Autoevaluacion;
    private javax.swing.JPanel jPanel_Principal;
    private javax.swing.JSlider jSlider_nivel;
    private javax.swing.JTextField jTextField_Edad;
    private javax.swing.JTextField jTextField_Nombre;
    private javax.swing.JTextField jTextField_Ocupacion;
    // End of variables declaration//GEN-END:variables
}
