/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front_End;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;

import javax.swing.ImageIcon;

import Back_End.SesionUsuario;
import Database.UsuariosDAO;

/**
 *
 * @author Karol
 */
public class Menu extends javax.swing.JPanel {

    private Runnable onCloseCallback;

    /**
     * Creates new form Menu
     */

    // Constructor simplificado
    public Menu(String pantallaActiva) {
        initComponents();
        configurarNavegacionTeclado();
        setBackground(new Color(250, 250, 250));
        setOpaque(true);

        // Obtener datos del usuario desde la sesión
        String nombreUsuario = SesionUsuario.getInstancia().getNombreUsuario();
        String correoUsuario = SesionUsuario.getInstancia().getCorreoUsuario();

        // Actualizar la etiqueta de bienvenida
        if (nombreUsuario != null && !nombreUsuario.isEmpty()) {
            Bienvenido.setText("Bienvenid@ " + nombreUsuario + "!");
        } else {
            Bienvenido.setText("Bienvenid@ User!");
        }

        // Cargar foto de perfil
        cargarFotoPerfil(correoUsuario);

        // Guardar correo para uso interno
        this.correoUsuario = correoUsuario != null ? correoUsuario : "";

        // Resto del código...
        this.pantallaActiva = pantallaActiva;
        marcarBotonActual();
    }

    public void setOnCloseCallback(Runnable callback) {
        this.onCloseCallback = callback;
    }

    private void marcarBotonActual() {
        switch (pantallaActiva) {
            case "Home" -> setActiveButton(Inicio);
            case "Videos" -> setActiveButton(Videos);
            case "Estadisticas" -> setActiveButton(Estadisticas);
            case "Perfil" -> setActiveButton(Perfil);
            case "Contactanos" -> setActiveButton(Contactanos);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new componentes.RoundedPanel();
        ButtonCerrarSesion = new javax.swing.JButton();
        Bienvenido = new javax.swing.JLabel();
        FotoPerfil = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Inicio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Videos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Estadisticas = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Perfil = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        Contactanos = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();

        roundedPanel1.setBackground(new java.awt.Color(250, 250, 250));
        roundedPanel1.setLeftRounded(false);

        ButtonCerrarSesion.setBackground(new java.awt.Color(30, 56, 136));
        ButtonCerrarSesion.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonCerrarSesion.setForeground(new java.awt.Color(250, 250, 250));
        ButtonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log-out.png"))); // NOI18N
        ButtonCerrarSesion.setText("Cerrar Sesión");
        ButtonCerrarSesion.setToolTipText("");
        ButtonCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCerrarSesionMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonCerrarSesionMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonCerrarSesionMouseExited(evt);
            }
        });
        ButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCerrarSesionActionPerformed(evt);
            }
        });

        Bienvenido.setFont(new java.awt.Font("Epunda Slab Medium", 0, 32)); // NOI18N
        Bienvenido.setText("Bienvenid@ User!");

        FotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 5.png"))); // NOI18N

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BlueExit.png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        Inicio.setBackground(new java.awt.Color(250, 250, 250));
        Inicio.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Home.png"))); // NOI18N
        Inicio.setText("Inicio");
        Inicio.setToolTipText("");
        Inicio.setBorderPainted(false);
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio.setFocusPainted(false);
        Inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Inicio.setIconTextGap(20);
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InicioMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                InicioMouseExited(evt);
            }
        });
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Videos.setBackground(new java.awt.Color(250, 250, 250));
        Videos.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Videos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Video.png"))); // NOI18N
        Videos.setText("Videos");
        Videos.setToolTipText("");
        Videos.setAlignmentX(0.5F);
        Videos.setBorderPainted(false);
        Videos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Videos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Videos.setIconTextGap(20);
        Videos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VideosMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VideosMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                VideosMouseExited(evt);
            }
        });
        Videos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideosActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        Estadisticas.setBackground(new java.awt.Color(250, 250, 250));
        Estadisticas.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Estadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Stats.png"))); // NOI18N
        Estadisticas.setText("Estadísticas");
        Estadisticas.setToolTipText("");
        Estadisticas.setAlignmentX(0.5F);
        Estadisticas.setBorderPainted(false);
        Estadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Estadisticas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Estadisticas.setIconTextGap(20);
        Estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstadisticasMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EstadisticasMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                EstadisticasMouseExited(evt);
            }
        });
        Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        Perfil.setBackground(new java.awt.Color(250, 250, 250));
        Perfil.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_1.png"))); // NOI18N
        Perfil.setText("Mi cuenta");
        Perfil.setToolTipText("");
        Perfil.setAlignmentX(0.5F);
        Perfil.setBorderPainted(false);
        Perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Perfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Perfil.setIconTextGap(20);
        Perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PerfilMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PerfilMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                PerfilMouseExited(evt);
            }
        });
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        Contactanos.setBackground(new java.awt.Color(250, 250, 250));
        Contactanos.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Contactanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Email.png"))); // NOI18N
        Contactanos.setText("Contáctanos");
        Contactanos.setToolTipText("");
        Contactanos.setAlignmentX(0.5F);
        Contactanos.setBorderPainted(false);
        Contactanos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contactanos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Contactanos.setIconTextGap(20);
        Contactanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactanosMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContactanosMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContactanosMouseExited(evt);
            }
        });
        Contactanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactanosActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
                roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout
                                .createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(roundedPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                roundedPanel1Layout.createSequentialGroup()
                                                        .addComponent(Close)
                                                        .addGap(18, 18, 18))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout
                                                .createSequentialGroup()
                                                .addGroup(roundedPanel1Layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                                                false)
                                                        .addComponent(jSeparator1)
                                                        .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Videos, javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator2,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Estadisticas,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator3,
                                                                javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(Perfil, javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator4)
                                                        .addComponent(Contactanos,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(jSeparator5,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE, 195,
                                                                javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(93, 93, 93))))
                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                .addGroup(roundedPanel1Layout
                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addGap(69, 69, 69)
                                                .addComponent(Bienvenido))
                                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(ButtonCerrarSesion))
                                        .addGroup(roundedPanel1Layout.createSequentialGroup()
                                                .addGap(80, 80, 80)
                                                .addComponent(FotoPerfil)))
                                .addContainerGap(82, Short.MAX_VALUE)));
        roundedPanel1Layout.setVerticalGroup(
                roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                roundedPanel1Layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addComponent(Close)
                                        .addGap(100, 100, 100)
                                        .addComponent(FotoPerfil)
                                        .addGap(33, 33, 33)
                                        .addComponent(Bienvenido)
                                        .addGap(40, 40, 40)
                                        .addComponent(Inicio)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Videos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Estadisticas)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Perfil)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(Contactanos)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(47, 47, 47)
                                        .addComponent(ButtonCerrarSesion)
                                        .addContainerGap(202, Short.MAX_VALUE)));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE));

    }// </editor-fold>//GEN-END:initComponents

    // Agregar en el constructor después de initComponents():
    private void configurarNavegacionTeclado() {
        // Hacer todos los botones enfocables
        Inicio.setFocusable(true);
        Videos.setFocusable(true);
        Estadisticas.setFocusable(true);
        Perfil.setFocusable(true);
        Contactanos.setFocusable(true);
        ButtonCerrarSesion.setFocusable(true);

        // Configurar acciones para Enter y Space en cada botón
        configurarAccionTeclado(Inicio, new Runnable() {
            public void run() {
                InicioMouseClicked(null);
            }
        });

        configurarAccionTeclado(Videos, new Runnable() {
            public void run() {
                VideosMouseClicked(null);
            }
        });

        configurarAccionTeclado(Estadisticas, new Runnable() {
            public void run() {
                EstadisticasMouseClicked(null);
            }
        });

        configurarAccionTeclado(Perfil, new Runnable() {
            public void run() {
                PerfilMouseClicked(null);
            }
        });

        configurarAccionTeclado(Contactanos, new Runnable() {
            public void run() {
                ContactanosMouseClicked(null);
            }
        });

        configurarAccionTeclado(ButtonCerrarSesion, new Runnable() {
            public void run() {
                ButtonCerrarSesionMouseClicked(null);
            }
        });

        // Configurar ESC para cerrar el menú
        this.getInputMap(javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW).put(
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0), "cerrarMenu");

        this.getActionMap().put("cerrarMenu", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                if (onCloseCallback != null) {
                    onCloseCallback.run();
                }
            }
        });
    }

    private void configurarAccionTeclado(javax.swing.JButton boton, Runnable accion) {
        // Enter key
        boton.getInputMap(javax.swing.JComponent.WHEN_FOCUSED).put(
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ENTER, 0), "pressed");
        boton.getActionMap().put("pressed", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                accion.run();
            }
        });

        // Space key
        boton.getInputMap(javax.swing.JComponent.WHEN_FOCUSED).put(
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_SPACE, 0), "spacePressed");
        boton.getActionMap().put("spacePressed", new javax.swing.AbstractAction() {
            @Override
            public void actionPerformed(java.awt.event.ActionEvent e) {
                accion.run();
            }
        });
    }

    // Método para marcar el botón activo (azul)
    public void setActiveButton(javax.swing.JButton activeButton) {
        java.awt.Color azul = new java.awt.Color(0, 102, 204);
        java.awt.Color gris = new java.awt.Color(240, 240, 240);

        javax.swing.JButton[] botones = { Inicio, Videos, Perfil, Contactanos, Estadisticas };

        for (javax.swing.JButton b : botones) {
            if (b == activeButton) {
                b.setBackground(azul);
                b.setForeground(Color.WHITE);
            } else {
                b.setBackground(gris);
                b.setForeground(Color.BLACK);
            }
        }
    }

    // Método para cargar la foto de perfil
    private void cargarFotoPerfil(String correo) {
        if (correo != null && !correo.isEmpty()) {
            UsuariosDAO dao = new UsuariosDAO();
            byte[] fotoBytes = dao.obtenerFotoPerfil(correo);
            
            // Usar un tamaño consistente, por ejemplo, 200x200
            final int TAMANO_IMAGEN = 200; 

            if (fotoBytes != null && fotoBytes.length > 0) {
                // Convertir bytes a ImageIcon circular
                ImageIcon imagenCircular = crearImagenCircular(fotoBytes, TAMANO_IMAGEN, TAMANO_IMAGEN); 
                if (imagenCircular != null) {
                    FotoPerfil.setIcon(imagenCircular);
                    // Ajustar el tamaño del JLabel para que coincida con la imagen circular
                    FotoPerfil.setPreferredSize(new java.awt.Dimension(TAMANO_IMAGEN, TAMANO_IMAGEN));
                    FotoPerfil.setSize(new java.awt.Dimension(TAMANO_IMAGEN, TAMANO_IMAGEN));
                    FotoPerfil.revalidate();
                    FotoPerfil.repaint();
                    return; // Salir si se cargó exitosamente
                }
            }
            // Si llegamos aquí, cargar foto por defecto
            cargarFotoPerfilDefecto(TAMANO_IMAGEN);
        }
    }
    
    private void cargarFotoPerfilDefecto(int size) {
        try {
            // Asegúrate de que la ruta del recurso es correcta
            ImageIcon iconoDefault = new ImageIcon(getClass().getResource("/Images/Group 5.png")); 
            if (iconoDefault != null) {
                // Crear imagen circular desde el icono por defecto
                ImageIcon imagenCircular = crearImagenCircularDeIcono(iconoDefault, size, size);
                if (imagenCircular != null) {
                    FotoPerfil.setIcon(imagenCircular);
                    // Ajustar el tamaño del JLabel
                    FotoPerfil.setPreferredSize(new java.awt.Dimension(size, size));
                    FotoPerfil.setSize(new java.awt.Dimension(size, size));
                    FotoPerfil.revalidate();
                    FotoPerfil.repaint();
                }
            }
        } catch (Exception e) {
            System.err.println("Error al cargar imagen por defecto en menú: " + e.getMessage());
        }
    }

    private ImageIcon crearImagenCircular(byte[] imageBytes, int width, int height) {
        try {
            ImageIcon originalIcon = new ImageIcon(imageBytes);
            // *** CORRECCIÓN: Ahora se creará la imagen circular ***
            return crearImagenCircularDeIcono(originalIcon, width, height);
        } catch (Exception e) {
            System.err.println("Error al crear imagen circular: " + e.getMessage());
            return null;
        }
    }

    // Método para crear imagen circular desde ImageIcon
    private ImageIcon crearImagenCircularDeIcono(ImageIcon originalIcon, int width, int height) {
        int size = Math.min(width, height); // Forzar que sea un cuadrado para un círculo
        
        java.awt.Image imagenOriginal = originalIcon.getImage();
        
        // Crear un buffer con transparencia para la imagen final
        BufferedImage circularImage = new BufferedImage(size, size, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = circularImage.createGraphics();
        
        // Configurar Hints para máxima calidad
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        g2d.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BICUBIC);
        
        // Crear un círculo como clip (máscara)
        java.awt.geom.Ellipse2D.Double circle = new java.awt.geom.Ellipse2D.Double(0, 0, size, size);
        
        // Aplicar el clip circular
        g2d.setClip(circle);
        
        // Dibujar la imagen redimensionada dentro del clip circular
        g2d.drawImage(imagenOriginal, 0, 0, size, size, null);
        
        // Dibujar un borde opcional (puedes comentar si no lo quieres)
        g2d.setClip(null);
        g2d.setColor(new Color(0x1E3888)); // Color azul de tu diseño
        g2d.setStroke(new java.awt.BasicStroke(2.0f));
        g2d.draw(circle);
        
        g2d.dispose();
        
        return new ImageIcon(circularImage);
    }

    private void ButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ButtonCerrarSesionActionPerformed

    private void ButtonCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ButtonCerrarSesionMouseExited
        ButtonCerrarSesion.setBackground(new Color(0x1E3888));
        ButtonCerrarSesion.setForeground(Color.WHITE);
    }// GEN-LAST:event_ButtonCerrarSesionMouseExited

    private void ButtonCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ButtonCerrarSesionMouseEntered
        ButtonCerrarSesion.setBackground(new Color(0xD9D9D9));
        ButtonCerrarSesion.setForeground(new Color(0x1E3888));
    }// GEN-LAST:event_ButtonCerrarSesionMouseEntered

    private void ButtonCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {
        // Cerrar sesión
        SesionUsuario.getInstancia().cerrarSesion();

        java.awt.Window ventanaActual = javax.swing.SwingUtilities.getWindowAncestor(this);

        // Abrir la ventana de LogIn
        login login = new login();
        login.setVisible(true);
        login.setLocationRelativeTo(null);

        if (ventanaActual != null) {
            ventanaActual.dispose();
        }
    }

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_InicioMouseClicked

        // Abrir la ventana de LogIn
        new Home().setVisible(true);
        javax.swing.SwingUtilities.getWindowAncestor(this).dispose();
    }// GEN-LAST:event_InicioMouseClicked

    private void InicioMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_InicioMouseEntered
        Inicio.setBackground(new Color(0x98CEFF));
        Inicio.setForeground(Color.BLACK);
    }// GEN-LAST:event_InicioMouseEntered

    private void InicioMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_InicioMouseExited
        Inicio.setBackground(new Color(0xFAFAFA));
        Inicio.setForeground(Color.BLACK);
    }// GEN-LAST:event_InicioMouseExited

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_InicioActionPerformed

    private void VideosMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_VideosMouseClicked
        java.awt.Window ventanaActual = javax.swing.SwingUtilities.getWindowAncestor(this);
        // Abrir la ventana de LogIn
        new Ejercicios().setVisible(true);

        if (ventanaActual != null) {
            ventanaActual.dispose();
        }
    }// GEN-LAST:event_VideosMouseClicked

    private void VideosMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_VideosMouseEntered
        Videos.setBackground(new Color(0x98CEFF));
        Videos.setForeground(Color.BLACK);
    }// GEN-LAST:event_VideosMouseEntered

    private void VideosMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_VideosMouseExited
        Videos.setBackground(new Color(0xFAFAFA));
        Videos.setForeground(Color.BLACK);
    }// GEN-LAST:event_VideosMouseExited

    private void VideosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_VideosActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_VideosActionPerformed

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_CloseMouseClicked
        if (onCloseCallback != null) {
            onCloseCallback.run(); // Notifica al Home que cierre el menú
        }
    }// GEN-LAST:event_CloseMouseClicked

    private void EstadisticasMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_EstadisticasMouseClicked
        java.awt.Window ventanaActual = javax.swing.SwingUtilities.getWindowAncestor(this);

        Estadisticas estadisticas = new Estadisticas();
        estadisticas.setVisible(true);
        estadisticas.setLocationRelativeTo(null);

        if (ventanaActual != null) {
            ventanaActual.dispose();
        }
    }// GEN-LAST:event_EstadisticasMouseClicked

    private void EstadisticasMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_EstadisticasMouseEntered
        // TODO add your handling code here:
    }// GEN-LAST:event_EstadisticasMouseEntered

    private void EstadisticasMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_EstadisticasMouseExited
        // TODO add your handling code here:
    }// GEN-LAST:event_EstadisticasMouseExited

    private void EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_EstadisticasActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_EstadisticasActionPerformed

    private void PerfilMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PerfilMouseClicked
        java.awt.Window ventanaActual = javax.swing.SwingUtilities.getWindowAncestor(this);
        // Abrir la ventana de LogIn
        Perfil Perfil = new Perfil();
        Perfil.setVisible(true);
        Perfil.setLocationRelativeTo(null); // Centrar en pantalla
        if (ventanaActual != null) {
            ventanaActual.dispose();
        }
    }// GEN-LAST:event_PerfilMouseClicked

    private void PerfilMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PerfilMouseEntered
        Perfil.setBackground(new Color(0x98CEFF));
        Perfil.setForeground(Color.BLACK);
    }// GEN-LAST:event_PerfilMouseEntered

    private void PerfilMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_PerfilMouseExited
        Perfil.setBackground(new Color(0xFAFAFA));
        Perfil.setForeground(Color.BLACK);
    }// GEN-LAST:event_PerfilMouseExited

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_PerfilActionPerformed

    private void ContactanosMouseClicked(java.awt.event.MouseEvent evt) {
        java.awt.Window ventanaActual = javax.swing.SwingUtilities.getWindowAncestor(this);

        // Abrir Contactanos sin parámetro (ya obtiene el correo de la sesión)
        Contactanos contactanos = new Contactanos();
        contactanos.setVisible(true);
        contactanos.setLocationRelativeTo(null);

        if (ventanaActual != null) {
            ventanaActual.dispose();
        }
    }

    private void ContactanosMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ContactanosMouseEntered
        Contactanos.setBackground(new Color(0x98CEFF));
        Contactanos.setForeground(Color.BLACK);
    }// GEN-LAST:event_ContactanosMouseEntered

    private void ContactanosMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ContactanosMouseExited
        Contactanos.setBackground(new Color(0xFAFAFA));
        Contactanos.setForeground(Color.BLACK);
    }// GEN-LAST:event_ContactanosMouseExited

    private void ContactanosActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_ContactanosActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_ContactanosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JButton ButtonCerrarSesion;
    private javax.swing.JLabel Close;
    private javax.swing.JButton Contactanos;
    private javax.swing.JButton Estadisticas;
    private javax.swing.JLabel FotoPerfil;
    private javax.swing.JButton Inicio;
    private javax.swing.JButton Perfil;
    private javax.swing.JButton Videos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private componentes.RoundedPanel roundedPanel1;
    
    private String pantallaActiva;
    private String correoUsuario = "";
    // End of variables declaration//GEN-END:variables
}
