/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front_End;

/**
 *
 * @author Karol
 */
public class MenuAccesibilidad extends javax.swing.JFrame {

    /**
     * Creates new form MenuAccesibilidad
     */
    public MenuAccesibilidad() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        exit = new javax.swing.JLabel();
        Text = new componentes.RoundedPanel();
        t = new javax.swing.JLabel();
        text = new javax.swing.JLabel();
        T = new javax.swing.JLabel();
        Contrast = new componentes.RoundedPanel();
        contrast = new javax.swing.JLabel();
        contrastIcon = new javax.swing.JLabel();
        Tittle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(217, 217, 217));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BlueExit.png"))); // NOI18N
        exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 16, -1, -1));

        Text.setBackground(new java.awt.Color(250, 250, 250));
        Text.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t.setFont(new java.awt.Font("Epunda Slab", 0, 30)); // NOI18N
        t.setText("T");
        Text.add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 50, -1, 30));

        text.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        text.setText("Cambiar tamaño");
        Text.add(text, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, -1, -1));

        T.setFont(new java.awt.Font("Epunda Slab", 0, 48)); // NOI18N
        T.setText("T");
        Text.add(T, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 40, -1, 40));

        jPanel1.add(Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(91, 137, 160, 140));

        Contrast.setBackground(new java.awt.Color(250, 250, 250));
        Contrast.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        contrast.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        contrast.setText("Contraste +");
        Contrast.add(contrast, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        contrastIcon.setFont(new java.awt.Font("Epunda Slab", 0, 48)); // NOI18N
        contrastIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Contrast.png"))); // NOI18N
        Contrast.add(contrastIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 30, 50, 60));

        jPanel1.add(Contrast, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 137, 160, 140));

        Tittle1.setFont(new java.awt.Font("Epunda Slab", 0, 24)); // NOI18N
        Tittle1.setText("Menú de Accesibilidad");
        jPanel1.add(Tittle1, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 27, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAccesibilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAccesibilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAccesibilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAccesibilidad.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAccesibilidad().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.RoundedPanel Contrast;
    private javax.swing.JLabel T;
    private componentes.RoundedPanel Text;
    private javax.swing.JLabel Tittle1;
    private javax.swing.JLabel contrast;
    private javax.swing.JLabel contrastIcon;
    private javax.swing.JLabel exit;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel t;
    private javax.swing.JLabel text;
    // End of variables declaration//GEN-END:variables
}
