/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front_End;

import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.geom.Ellipse2D;
import java.awt.image.BufferedImage;

import javax.swing.ImageIcon;
import javax.swing.JLayeredPane;
import javax.swing.JOptionPane;
import javax.swing.Timer;

import Back_End.SesionUsuario;
import Back_End.Usuario;
import Database.UsuariosDAO;

/**
 *
 * @author Karol
 */
public class Perfil extends javax.swing.JFrame {

    private Menu menuPanel;
    private boolean menuVisible = false;
    private int menuWidth = 370;
    private int menuX = -menuWidth;
    int xmouse, ymouse;

    // Nuevas variables para controlar la capa de bloqueo
    private JLayeredPane layeredPane;

    /**
     * Creates new form Perfil
     */
    public Perfil() {
        setUndecorated(true);

        initComponents();
        cargarDatosUsuario();
        desactivarCampos();
        verificarComponentes();

        // Configurar layered pane
        layeredPane = getLayeredPane();

        setSize(1440, 1024);
        setLocationRelativeTo(null);
        setResizable(false);

        menuPanel = new Menu("Perfil");
        menuPanel.setBounds(menuX, 0, menuWidth, getHeight());
        menuPanel.setVisible(true);
        menuPanel.setOpaque(true);
        menuPanel.setBackground(new Color(250, 250, 250));
        menuPanel.setOnCloseCallback(() -> {
            toggleMenu(null);
        });

        getContentPane().add(menuPanel);
        getContentPane().setComponentZOrder(menuPanel, 0);

        // Añadir el menú a una capa superior
        layeredPane.add(menuPanel, JLayeredPane.POPUP_LAYER);

        revalidate();
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        roundedPanel1 = new componentes.RoundedPanel();
        nombres = new javax.swing.JLabel();
        nameText = new componentes.IconTextField();
        Apellidos = new javax.swing.JLabel();
        ApellidosText = new componentes.IconTextField();
        Fnacimiento = new javax.swing.JLabel();
        DateText = new componentes.IconTextField();
        Telefono = new javax.swing.JLabel();
        celText = new componentes.IconTextField();
        Correo = new javax.swing.JLabel();
        CorreoText = new componentes.IconTextField();
        password = new javax.swing.JLabel();
        PasswordText = new javax.swing.JPasswordField();
        numIDLabel = new javax.swing.JLabel();
        numIDText = new componentes.IconTextField();
        IDType = new javax.swing.JComboBox<>();
        FotoPerfil = new javax.swing.JLabel();
        TypeIDLabel = new javax.swing.JLabel();
        ButtonEdit = new javax.swing.JButton();
        roundedPanel2 = new componentes.RoundedPanel();
        TipoPlan = new javax.swing.JLabel();
        PlanLabel = new javax.swing.JLabel();
        ButtonPremium = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        Menu = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Titulo1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        roundedPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        // Agrega estas propiedades para la foto
        FotoPerfil.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FotoPerfil.setVerticalAlignment(javax.swing.SwingConstants.CENTER);

        // Y AÑADE ESTA LÍNEA para posicionar la foto en el layout:
        roundedPanel1.add(FotoPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 210, 200));

        

        nombres.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        nombres.setText("Nombres");
        roundedPanel1.add(nombres, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 470, -1, -1));

        nameText.setForeground(new java.awt.Color(142, 142, 147));
        nameText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        nameText.setIconGap(2);
        nameText.setText("Escribe tus nombres");
        nameText.setToolTipText("");
        nameText.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        nameText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                nameTextMousePressed(evt);
            }
        });
        nameText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameTextActionPerformed(evt);
            }
        });
        roundedPanel1.add(nameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 510, 230, 35));

        Apellidos.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Apellidos.setText("Apellidos");
        roundedPanel1.add(Apellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 470, -1, -1));

        ApellidosText.setForeground(new java.awt.Color(142, 142, 147));
        ApellidosText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user.png"))); // NOI18N
        ApellidosText.setIconGap(2);
        ApellidosText.setText("Escribe tus apellidos");
        ApellidosText.setToolTipText("");
        ApellidosText.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        ApellidosText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                ApellidosTextMousePressed(evt);
            }
        });
        ApellidosText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ApellidosTextActionPerformed(evt);
            }
        });
        roundedPanel1.add(ApellidosText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 510, 230, 35));

        Fnacimiento.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Fnacimiento.setText("Fecha de Nacimiento");
        roundedPanel1.add(Fnacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 570, -1, -1));

        DateText.setForeground(new java.awt.Color(142, 142, 147));
        DateText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/date.png"))); // NOI18N
        DateText.setIconGap(2);
        DateText.setText("dd/mm/aa");
        DateText.setToolTipText("");
        DateText.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        DateText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                DateTextMousePressed(evt);
            }
        });
        DateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DateTextActionPerformed(evt);
            }
        });
        roundedPanel1.add(DateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 230, 35));

        Telefono.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Telefono.setText("Teléfono");
        roundedPanel1.add(Telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, -1, -1));

        celText.setForeground(new java.awt.Color(142, 142, 147));
        celText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mynaui_telephone.png"))); // NOI18N
        celText.setIconGap(2);
        celText.setText("Número de Teléfono");
        celText.setToolTipText("");
        celText.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        celText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                celTextMousePressed(evt);
            }
        });
        roundedPanel1.add(celText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 610, 230, 35));

        Correo.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Correo.setText("Correo Electrónico");
        roundedPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 680, -1, -1));

        CorreoText.setForeground(new java.awt.Color(142, 142, 147));
        CorreoText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/correo.png"))); // NOI18N
        CorreoText.setText("Escribe tu Correo");
        CorreoText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CorreoTextMouseClicked(evt);
            }
        });
        CorreoText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CorreoTextActionPerformed(evt);
            }
        });
        roundedPanel1.add(CorreoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 720, 230, 35));

        password.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        password.setText("Contraseña");
        roundedPanel1.add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 680, -1, -1));

        PasswordText.setFont(new java.awt.Font("Lato", 0, 12)); // NOI18N
        PasswordText.setForeground(new java.awt.Color(142, 142, 147));
        PasswordText.setText("jPasswordField1");
        PasswordText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                PasswordTextMousePressed(evt);
            }
        });
        PasswordText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextActionPerformed(evt);
            }
        });
        roundedPanel1.add(PasswordText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 720, 230, 35));

        numIDLabel.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        numIDLabel.setText("N° de Documento");
        roundedPanel1.add(numIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 370, -1, -1));

        numIDText.setForeground(new java.awt.Color(142, 142, 147));
        numIDText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/id-card.png"))); // NOI18N
        numIDText.setIconGap(2);
        numIDText.setText("1234567891");
        numIDText.setToolTipText("");
        numIDText.setFont(new java.awt.Font("Lato", 0, 15)); // NOI18N
        numIDText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                numIDTextMousePressed(evt);
            }
        });
        roundedPanel1.add(numIDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 410, 230, 35));

        IDType.setFont(new java.awt.Font("Lato", 0, 16)); // NOI18N
        IDType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C.C", "C.E", "T.I", "Pasaporte" }));
        IDType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDTypeActionPerformed(evt);
            }
        });
        roundedPanel1.add(IDType, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 420, 230, 35));

        TypeIDLabel.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        TypeIDLabel.setText("Tipo de Documento");
        roundedPanel1.add(TypeIDLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 380, -1, -1));

        ButtonEdit.setBackground(new java.awt.Color(152, 206, 255));
        ButtonEdit.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonEdit.setText("Editar");
        ButtonEdit.setToolTipText("");
        ButtonEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEdit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonEditMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonEditMouseExited(evt);
            }
        });
        ButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEditActionPerformed(evt);
            }
        });
        roundedPanel1.add(ButtonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 800, 140, 40));

        roundedPanel2.setBackground(new java.awt.Color(255, 255, 255));

        TipoPlan.setFont(new java.awt.Font("Epunda Slab", 1, 24)); // NOI18N
        TipoPlan.setText("Tipo de Plan");
        PlanLabel.setFont(new java.awt.Font("Epunda Slab", 1, 24)); // NOI18N
        PlanLabel.setText("Tipo de Plan");

        ButtonPremium.setBackground(new java.awt.Color(152, 206, 255));
        ButtonPremium.setFont(new java.awt.Font("Epunda Slab", 0, 15)); // NOI18N
        ButtonPremium.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Premium.png"))); // NOI18N
        ButtonPremium.setText("Conviertete en Premium");
        ButtonPremium.setToolTipText("");
        ButtonPremium.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonPremium.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonPremiumMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonPremiumMouseExited(evt);
            }
        });
        ButtonPremium.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonPremiumActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout roundedPanel2Layout = new javax.swing.GroupLayout(roundedPanel2);
        roundedPanel2.setLayout(roundedPanel2Layout);
        roundedPanel2Layout.setHorizontalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addGroup(roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel2Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(ButtonPremium))
                    .addGroup(roundedPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(TipoPlan)))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(PlanLabel)
                .addGap(86, 86, 86))
        );
        roundedPanel2Layout.setVerticalGroup(
            roundedPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundedPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(TipoPlan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 117, Short.MAX_VALUE)
                .addComponent(PlanLabel)
                .addGap(40, 40, 40)
                .addComponent(ButtonPremium, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );

        roundedPanel1.add(roundedPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 60, 260, 250));

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 90, 700, 900));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Background_1.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 1440, 984));

        jPanel2.setBackground(new java.awt.Color(30, 56, 136));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleMenu(evt);
            }
        });
        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 30));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel2.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 30, 40));

        Titulo1.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("PERFIL");
        jPanel2.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void desactivarCampos() {
        nameText.setEnabled(false);
        ApellidosText.setEnabled(false);
        DateText.setEnabled(false);
        celText.setEnabled(false);
        CorreoText.setEnabled(false);
        PasswordText.setEnabled(false);
        numIDText.setEnabled(false);
        IDType.setEnabled(false);
    }

    // En Perfil.java, agrega este método y llámalo en el constructor después de initComponents()
    private void verificarComponentes() {
        System.out.println("FotoPerfil en Perfil es null: " + (FotoPerfil == null));
        if (FotoPerfil != null) {
            System.out.println("Ubicación de FotoPerfil: " + FotoPerfil.getLocation());
            System.out.println("Tamaño de FotoPerfil: " + FotoPerfil.getSize());
            System.out.println("Es visible: " + FotoPerfil.isVisible());
        }
    }


    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {                                  
        System.exit(0);
    }                                 

    private void nameTextMousePressed(java.awt.event.MouseEvent evt) {                                      
    }                                     

    private void nameTextActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void ApellidosTextMousePressed(java.awt.event.MouseEvent evt) {                                           
    }                                          

    private void ApellidosTextActionPerformed(java.awt.event.ActionEvent evt) {                                              
    }                                             

    private void DateTextMousePressed(java.awt.event.MouseEvent evt) {                                      
    }                                     

    private void DateTextActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void celTextMousePressed(java.awt.event.MouseEvent evt) {                                     
    }                                    

    private void CorreoTextMouseClicked(java.awt.event.MouseEvent evt) {                                        
    }                                       

    private void CorreoTextActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void PasswordTextMousePressed(java.awt.event.MouseEvent evt) {                                          
    }                                         

    private void PasswordTextActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void numIDTextMousePressed(java.awt.event.MouseEvent evt) {                                       
    }                                      

    private void IDTypeActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    }                                      

    private void ButtonPremiumMouseEntered(java.awt.event.MouseEvent evt) {                                          
        ButtonPremium.setBackground(new Color(0x1E3888));
        ButtonPremium.setForeground(Color.WHITE);
    }                                         

    private void ButtonPremiumMouseExited(java.awt.event.MouseEvent evt) {                                         
        ButtonPremium.setBackground(new Color(0x98CEFF));
        ButtonPremium.setForeground(Color.BLACK);
    }                                        

    private void ButtonPremiumActionPerformed(java.awt.event.ActionEvent evt) {                                             
        // TODO add your handling code here:
    }                                            

    private void ButtonEditActionPerformed(java.awt.event.ActionEvent evt) {                                              
        if (!modoEdicion) {
            // PASAR A MODO EDICIÓN
            activarCampos();
            ButtonEdit.setText("Guardar");
            modoEdicion = true;
        } else {
            // GUARDAR CAMBIOS
            guardarCambios();
            desactivarCampos();
            ButtonEdit.setText("Editar");
            modoEdicion = false;
        }
    }                                             

    private void ButtonEditMouseExited(java.awt.event.MouseEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void ButtonEditMouseEntered(java.awt.event.MouseEvent evt) {                                           
        // TODO add your handling code here:
    }            
    
    private void toggleMenu(java.awt.event.MouseEvent evt) {
        if (menuVisible) {
            // Ocultar menú
            Timer slideOut = new Timer(2, e -> {
                if (menuX > -menuWidth) {
                    menuX -= 10;
                    menuPanel.setLocation(menuX, 0);
                } else {
                    ((Timer) e.getSource()).stop();
                    menuVisible = false;
                    // Eliminar esta línea: glassPane.setVisible(false);
                }
            });
            slideOut.start();
        } else {
            // Mostrar menú
            // Eliminar esta línea: glassPane.setVisible(true);
            Timer slideIn = new Timer(2, e -> {
                if (menuX < 0) {
                    menuX += 10;
                    menuPanel.setLocation(menuX, 0);
                } else {
                    ((Timer) e.getSource()).stop();
                    menuVisible = true;
                }
            });
            slideIn.start();
        }
    }

    private void cargarDatosUsuario() {
        SesionUsuario sesion = SesionUsuario.getInstancia();
        String correo = sesion.getCorreoUsuario();

        UsuariosDAO dao = new UsuariosDAO();
        Usuario u = dao.obtenerUsuarioPorCorreo(correo);

        if (u != null) {
            nameText.setText(u.getNombres());
            ApellidosText.setText(u.getApellidos());
            CorreoText.setText(u.getCorreo());
            celText.setText(u.getTelefono());
            DateText.setText(String.valueOf(u.getFechaNacimiento()));
            numIDText.setText(u.getNumeroId());
            IDType.setSelectedItem(u.getTipoId());

            // Cargar foto de perfil
            cargarFotoPerfil(correo);


            if (u.isEsPremium()) {
                PlanLabel.setText("Premium");
                PlanLabel.setForeground(new Color(220, 180, 0)); // Dorado
                ButtonPremium.setText("Ver beneficios");
            } else {
                PlanLabel.setText("Gratuito");
                PlanLabel.setForeground(new Color(30, 56, 136)); // Azul
                ButtonPremium.setText("Hazte Premium");

            }

            // Si tienes más campos, agrégalos
        }

    }

      // Método para cargar foto de perfil (similar al del Menu)
    private void cargarFotoPerfil(String correo) {
        if (correo != null && !correo.isEmpty()) {
            UsuariosDAO dao = new UsuariosDAO();
            byte[] fotoBytes = dao.obtenerFotoPerfil(correo);
            
            if (fotoBytes != null && fotoBytes.length > 0) {
                ImageIcon imagenCircular = crearImagenCircular(fotoBytes, 210, 200);
                FotoPerfil.setIcon(imagenCircular);
                FotoPerfil.setPreferredSize(new java.awt.Dimension(210,200));
            } else {
                ImageIcon iconoDefault = new ImageIcon(getClass().getResource("/Images/Group 5.png"));
                java.awt.Image imagenRedimensionada = iconoDefault.getImage().getScaledInstance(210, 200, java.awt.Image.SCALE_SMOOTH);
                ImageIcon imagenCircular = crearImagenCircularDeIcono(new ImageIcon(imagenRedimensionada), 210, 200);
                FotoPerfil.setIcon(imagenCircular);
            }
        }
    }

    // Los mismos métodos crearImagenCircular y crearImagenCircularDeIcono del Menu
    private ImageIcon crearImagenCircular(byte[] imageBytes, int width, int height) {
        try {
            ImageIcon originalIcon = new ImageIcon(imageBytes);
            return crearImagenCircularDeIcono(originalIcon, width, height);
        } catch (Exception e) {
            System.err.println("Error al crear imagen circular: " + e.getMessage());
            return null;
        }
    }

    private ImageIcon crearImagenCircularDeIcono(ImageIcon originalIcon, int width, int height) {
        java.awt.Image imagenOriginal = originalIcon.getImage();
        java.awt.Image imagenRedimensionada = imagenOriginal.getScaledInstance(width, height, java.awt.Image.SCALE_SMOOTH);
        
        BufferedImage mask = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        Graphics2D g2d = mask.createGraphics();
        
        g2d.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        
        Ellipse2D.Double forma = new Ellipse2D.Double(0, 0, width, height);
        g2d.setClip(forma);
        g2d.drawImage(imagenRedimensionada, 0, 0, width, height, null);
        
        g2d.dispose();
        
        return new ImageIcon(mask);
    }

    private void activarCampos() {
        nameText.setEnabled(true);
        ApellidosText.setEnabled(true);
        DateText.setEnabled(true);
        celText.setEnabled(true);
        CorreoText.setEnabled(true);
        PasswordText.setEnabled(true);
        numIDText.setEnabled(true);
        IDType.setEnabled(true);
    }

// Modifica el método guardarCambios() en Perfil.java
    private void guardarCambios() {
        try {
            // Obtener el usuario actual de la sesión
            SesionUsuario sesion = SesionUsuario.getInstancia();
            String correoActual = sesion.getCorreoUsuario();
            
            // Crear objeto usuario con los datos actualizados
            Usuario u = new Usuario();
            u.setNombres(nameText.getText());
            u.setApellidos(ApellidosText.getText());
            u.setCorreo(CorreoText.getText());
            u.setTelefono(celText.getText());
            u.setNumeroId(numIDText.getText());
            u.setTipoId(IDType.getSelectedItem().toString());

            // Manejar fecha de nacimiento
            try {
                String fechaStr = DateText.getText();
                // Si la fecha está en formato dd/mm/aaaa, convertir a aaaa-mm-dd
                if (fechaStr.contains("/")) {
                    String[] partes = fechaStr.split("/");
                    if (partes.length == 3) {
                        fechaStr = partes[2] + "-" + partes[1] + "-" + partes[0];
                    }
                }
                java.sql.Date fechaSQL = java.sql.Date.valueOf(fechaStr); 
                u.setFechaNacimiento(fechaSQL);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Formato de fecha incorrecto. Use yyyy-MM-dd o dd/MM/yyyy");
                return;
            }

            // Verificar que el correo no esté vacío
            if (u.getCorreo() == null || u.getCorreo().trim().isEmpty()) {
                JOptionPane.showMessageDialog(this, "El correo electrónico no puede estar vacío");
                return;
            }

            UsuariosDAO dao = new UsuariosDAO();
            boolean actualizado = dao.actualizarUsuario(u);

            // Verificar si se quiere cambiar la contraseña
            String nuevaContrasena = new String(PasswordText.getPassword());
            boolean contrasenaModificada = !nuevaContrasena.isEmpty() && !nuevaContrasena.equals("jPasswordField1");
            
            if (contrasenaModificada) {
                // Pedir contraseña actual para verificar
                String contrasenaActual = JOptionPane.showInputDialog(this,
                    "Para cambiar la contraseña, ingresa tu contraseña actual:",
                    "Verificación de Contraseña",
                    JOptionPane.QUESTION_MESSAGE);
                
                if (contrasenaActual != null && !contrasenaActual.trim().isEmpty()) {
                    // Verificar contraseña actual
                    if (dao.verificarUsuario(correoActual, contrasenaActual)) {
                        // Contraseña actual correcta, cambiar la contraseña
                        boolean contrasenaActualizada = dao.actualizarContrasena(u.getCorreo(), nuevaContrasena);
                        if (contrasenaActualizada) {
                            JOptionPane.showMessageDialog(this, "Contraseña actualizada con éxito");
                            // Limpiar el campo de contraseña después de guardar
                            PasswordText.setText("jPasswordField1");
                            PasswordText.setEchoChar((char)0);
                        } else {
                            JOptionPane.showMessageDialog(this, 
                                "Error al actualizar la contraseña, pero los demás datos se guardaron.",
                                "Advertencia", 
                                JOptionPane.WARNING_MESSAGE);
                        }
                    } else {
                        JOptionPane.showMessageDialog(this,
                            "❌ Contraseña actual incorrecta. La contraseña no se cambiará.",
                            "Error de Verificación",
                            JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(this,
                        "Verificación cancelada. La contraseña no se cambiará.",
                        "Verificación Cancelada",
                        JOptionPane.WARNING_MESSAGE);
                }
            }

            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Datos actualizados con éxito");
                // Actualizar la sesión si el correo cambió
                if (!correoActual.equals(u.getCorreo())) {
                    sesion.iniciarSesion(u.getCorreo(), u.getNombres());
                }
            } else {
                JOptionPane.showMessageDialog(this, "Error al actualizar los datos. Verifique la información.");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Perfil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Perfil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Apellidos;
    private componentes.IconTextField ApellidosText;
    private javax.swing.JButton ButtonPremium;
    private javax.swing.JButton ButtonEdit;
    private javax.swing.JLabel Correo;
    private componentes.IconTextField CorreoText;
    private componentes.IconTextField DateText;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Fnacimiento;
    private javax.swing.JLabel TipoPlan;
    private javax.swing.JLabel PlanLabel;
    private javax.swing.JLabel FotoPerfil;
    private javax.swing.JLabel TypeIDLabel;
    private javax.swing.JComboBox<String> IDType;
    private javax.swing.JLabel Menu;
    private javax.swing.JPasswordField PasswordText;
    private javax.swing.JLabel Telefono;
    private javax.swing.JLabel Titulo1;
    private componentes.IconTextField celText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private componentes.IconTextField nameText;
    private javax.swing.JLabel nombres;
    private javax.swing.JLabel numIDLabel;
    private componentes.IconTextField numIDText;
    private javax.swing.JLabel password;
    private componentes.RoundedPanel roundedPanel1;
    private componentes.RoundedPanel roundedPanel2;
    private boolean modoEdicion = false;
    // End of variables declaration                   
}