/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Front_End;

import Back_End.StripeCheckoutService;
import Back_End.StripeLocalServer;
import Database.UsuariosDAO;
import Back_End.SesionUsuario;

import java.awt.Desktop;
import java.awt.event.ActionEvent;
import java.net.URI;

import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author usuario
 */
public class VentanaPagoPremium1 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaPagoPremium1.class.getName());
    private SesionUsuario sesion;
    private int idUsuario;

    // Para mover la ventana (barra superior)
    int xmouse, ymouse;
    /**
     * Creates new form VentanaPagoPremium1
     */
    public VentanaPagoPremium1(SesionUsuario sesion, JFrame ventanaPadre) {
        this.sesion = sesion;
        this.idUsuario = sesion.getUsuarioActual().getIdUsuario();
        initComponents();
        initFunciones();

        setShape(new java.awt.geom.RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));

        // Centrar respecto a la ventana del perfil
        setLocationRelativeTo(ventanaPadre);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        btnComprar = new javax.swing.JButton();
        infoText = new javax.swing.JLabel();
        barra = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setResizable(false);

        bg.setBackground(new java.awt.Color(255, 255, 255));
        bg.setPreferredSize(new java.awt.Dimension(704, 509));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnComprar.setBackground(new java.awt.Color(152, 206, 255));
        btnComprar.setFont(new java.awt.Font("Epunda Slab", 0, 24)); // NOI18N
        btnComprar.setText("Suscribirse");
        btnComprar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnComprar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnComprarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnComprarMouseExited(evt);
            }
        });
        
        bg.add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 210, 50));

        infoText.setFont(new java.awt.Font("SansSerif", 0, 14)); // NOI18N
        infoText.setForeground(new java.awt.Color(0, 0, 0));
        infoText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/premium.png"))); // NOI18N
        //infoText.setText("<html><body><center>¡Mejora tu experiencia con Flex-IA Premium!<br><br>Al suscribirte a nuestro plan premium, obtendrás acceso ilimitado a todas las funciones avanzadas de Flex-IA, incluyendo:<br><br>- Respuestas más rápidas y precisas.<br>- Acceso prioritario a nuevas funcionalidades.<br>- Soporte técnico dedicado.<br><br>¡No pierdas la oportunidad de llevar tu experiencia al siguiente nivel!<br>Haz clic en 'Suscribirse' para comenzar tu viaje con Flex-IA Premium hoy mismo.</center></body></html>");
        
        
        bg.add(infoText, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 680, 350));

        barra.setBackground(new java.awt.Color(30, 56, 136));
        barra.setPreferredSize(new java.awt.Dimension(704, 40));
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("FLEX-IA");
        barra.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, -1, 40));

        // Botón minimizar (estilo login)
        minimizebtn = new javax.swing.JPanel();
        minimizetxt = new javax.swing.JLabel();
        minimizebtn.setBackground(new java.awt.Color(30, 56, 136));
        minimizebtn.setLayout(new java.awt.BorderLayout());
        minimizetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizetxt.setText("-");
        minimizetxt.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 30));
        minimizetxt.setForeground(new java.awt.Color(250, 250, 250));
        minimizetxt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        minimizetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizetxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizetxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizetxtMouseExited(evt);
            }
        });
        minimizebtn.add(minimizetxt, java.awt.BorderLayout.CENTER);
        barra.add(minimizebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(576, 0, 60, 40));

        // Botón cerrar (reutiliza Exit como label)
        Closebtn = new javax.swing.JPanel();
        Closebtn.setBackground(new java.awt.Color(30, 56, 136));
        Closebtn.setLayout(new java.awt.BorderLayout());

        Exit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitMouseExited(evt);
            }
        });
        Closebtn.add(Exit, java.awt.BorderLayout.CENTER);
        barra.add(Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(644, 0, 60, 40));

        bg.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnComprarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseEntered
        btnComprar.setBackground(new java.awt.Color(0x1E3888));
        btnComprar.setForeground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_btnComprarMouseEntered

    private void btnComprarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnComprarMouseExited
        btnComprar.setBackground(new java.awt.Color(0x98CEFF));
        btnComprar.setForeground(new java.awt.Color(0, 0, 0));
    }//GEN-LAST:event_btnComprarMouseExited
    
    private void barraMousePressed(java.awt.event.MouseEvent evt) {
        xmouse = evt.getX();
        ymouse = evt.getY();
    }

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }

    private void ExitMouseEntered(java.awt.event.MouseEvent evt) {
        Closebtn.setBackground(java.awt.Color.red);
    }

    private void ExitMouseExited(java.awt.event.MouseEvent evt) {
        Closebtn.setBackground(new java.awt.Color(30, 56, 136));
    }

    private void minimizetxtMouseEntered(java.awt.event.MouseEvent evt) {
        minimizebtn.setBackground(java.awt.Color.decode("#2e4ca9"));
    }

    private void minimizetxtMouseExited(java.awt.event.MouseEvent evt) {
        minimizebtn.setBackground(new java.awt.Color(30, 56, 136));
    }

    private void minimizetxtMouseClicked(java.awt.event.MouseEvent evt) {
        this.setState(javax.swing.JFrame.ICONIFIED);
    }

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {
        dispose(); // cerrar solo la ventana
    }

    private void initFunciones() {
        // Acción del botón de compra
        btnComprar.addActionListener((ActionEvent e) -> procesarPago());
    }
    private StripeLocalServer server;
    private void procesarPago() {
        try {
            // Crear servicio Stripe
            StripeCheckoutService checkout = new StripeCheckoutService();

            // Generar sesión de pago para el usuario
            String checkoutUrl = checkout.crearSesionPago(idUsuario);

            // Solo iniciar el servidor si aún no está iniciado
            if (server == null) {
                server = new StripeLocalServer(new UsuariosDAO(), sesion);
                server.iniciarServidor();
            }

            // Abrir navegador con la sesión de Stripe
            Desktop.getDesktop().browse(new URI(checkoutUrl));

            // Mostrar mensaje de redirección
            JOptionPane.showMessageDialog(
                this,
                "Redirigiendo a Stripe…",
                "Procesando",
                JOptionPane.INFORMATION_MESSAGE
            );

            // Cerrar ventana
            dispose();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(
                this,
                "Ocurrió un error al iniciar el pago.\nVer consola para detalles.",
                "Error",
                JOptionPane.ERROR_MESSAGE
            );
            ex.printStackTrace();
        }
    }

    /**
     * @param args the command line arguments
     */

    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            // Aquí puedes pasar la sesión real del usuario
            SesionUsuario sesionDemo = null; // reemplaza con tu sesión real
            JFrame ventanaPerfilDemo = null; // reemplaza con tu ventana de perfil real
            new VentanaPagoPremium1(sesionDemo, ventanaPerfilDemo).setVisible(true);
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Exit;
    private javax.swing.JPanel Closebtn;
    private javax.swing.JPanel minimizebtn;
    private javax.swing.JLabel minimizetxt;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel barra;
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel infoText;
    // End of variables declaration//GEN-END:variables
}
