package Login;

import java.awt.*;

/**
 *
 * @author Karol
 */
public class RecuperarContrasena extends javax.swing.JFrame {
    
    private String correoUsuario;
    /**
     * Creates new form RecuperarContrasena
     */
    public RecuperarContrasena(String correoUsuario) {
        this.correoUsuario = correoUsuario;
        initComponents();
        // Mostrar el correo en el campo de texto
        MailText.setText(correoUsuario);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        MailText = new componentes.IconTextField();
        ValidarButton = new javax.swing.JButton();
        Codigo = new javax.swing.JLabel();
        Correo = new javax.swing.JLabel();
        Chek = new javax.swing.JLabel();
        EnviarButton = new javax.swing.JButton();
        CodeText = new componentes.IconTextField();
        Title = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(400, 320));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        MailText.setForeground(new java.awt.Color(153, 153, 153));
        MailText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/mail.png"))); // NOI18N
        MailText.setIconGap(8);
        MailText.setEditable(false);
        MailText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MailTextActionPerformed(evt);
            }
        });
        jPanel1.add(MailText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 210, 35));

        ValidarButton.setBackground(new java.awt.Color(152, 206, 255));
        ValidarButton.setFont(new java.awt.Font("Epunda Slab", 0, 14)); // NOI18N
        ValidarButton.setText("Validar código");
        ValidarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ValidarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ValidarButtonMouseExited(evt);
            }
        });
        ValidarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidarButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ValidarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, 35));

        Codigo.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        Codigo.setText("Código:");
        Codigo.setToolTipText("");
        jPanel1.add(Codigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, -1, -1));

        Correo.setFont(new java.awt.Font("Epunda Slab", 0, 18)); // NOI18N
        Correo.setText("Correo Eléctronico:");
        Correo.setToolTipText("");
        jPanel1.add(Correo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, -1));

        Chek.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Group 37.png"))); // NOI18N
        jPanel1.add(Chek, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 220, -1, -1));

        EnviarButton.setBackground(new java.awt.Color(30, 56, 136));
        EnviarButton.setFont(new java.awt.Font("Epunda Slab", 0, 14)); // NOI18N
        EnviarButton.setForeground(new java.awt.Color(250, 250, 250));
        EnviarButton.setText("Enviar código");
        EnviarButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EnviarButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EnviarButtonMouseExited(evt);
            }
        });
        jPanel1.add(EnviarButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 130, 110, 35));

        CodeText.setForeground(new java.awt.Color(153, 153, 153));
        CodeText.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cuida_number-outline.png"))); // NOI18N
        CodeText.setIconGap(8);
        CodeText.setText("12345");
        CodeText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CodeTextMouseClicked(evt);
            }
        });
        jPanel1.add(CodeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 140, 35));

        Title.setFont(new java.awt.Font("Epunda Slab SemiBold", 1, 20)); // NOI18N
        Title.setText("Recuperación de Contraseña");
        Title.setToolTipText("");
        jPanel1.add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 50, -1, -1));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 310, 10));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>                        

    private void MailTextActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
    }                                        

    private void ValidarButtonActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void ValidarButtonMouseEntered(java.awt.event.MouseEvent evt) {                                           
        ValidarButton.setBackground(new Color(0x1E3888));
        ValidarButton.setForeground(Color.WHITE);
    }                                          

    private void ValidarButtonMouseExited(java.awt.event.MouseEvent evt) {                                          
        ValidarButton.setBackground(new Color(0x98CEFF));
        ValidarButton.setForeground(Color.BLACK);
    }                                         

    private void EnviarButtonMouseEntered(java.awt.event.MouseEvent evt) {                                          
        EnviarButton.setBackground(new Color(0xD9D9D9));
        EnviarButton.setForeground(new Color(0x1E3888));
    }                                         

    private void EnviarButtonMouseExited(java.awt.event.MouseEvent evt) {                                         
        EnviarButton.setBackground(new Color(0x1E3888));
        EnviarButton.setForeground(Color.WHITE);
    }                                        

    private void CodeTextMouseClicked(java.awt.event.MouseEvent evt) {                                      
        CodeText.setText("");
    }                                     

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecuperarContrasena.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
    }

    // Variables declaration - do not modify                     
    private javax.swing.JLabel Chek;
    private componentes.IconTextField CodeText;
    private javax.swing.JLabel Codigo;
    private javax.swing.JLabel Correo;
    private javax.swing.JButton EnviarButton;
    private componentes.IconTextField MailText;
    private javax.swing.JLabel Title;
    private javax.swing.JButton ValidarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration                   
}