/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Color;

import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;

import Login.FuenteUtil;
import SignIn.SesionUsuario;

import static SignIn.CorreoService.enviarCorreoConReplyTo;

/**
 *
 * @author Karol
 */
public class Contactanos extends javax.swing.JFrame {
    private Menu menuPanel;
    private boolean menuVisible = false;
    private int menuWidth = 370;
    private int menuX = -menuWidth;
    int xmouse, ymouse;

    public Contactanos() {
        setUndecorated(true);
        initComponents();

        // Obtener el correo del usuario logueado desde la sesión
        String correoUsuario = SesionUsuario.getInstancia().getCorreoUsuario();

        // Verificar si hay un usuario logueado
        if (correoUsuario == null || correoUsuario.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "No hay usuario logueado. Por favor inicie sesión.",
                    "Error de sesión",
                    JOptionPane.ERROR_MESSAGE);
            this.dispose();
            return;
        }

        // Crear menú después de que la interfaz esté lista
        menuPanel = new Menu("Contactanos");
        menuPanel.setBounds(menuX, 0, menuWidth, getHeight());
        menuPanel.setVisible(true);
        menuPanel.setOpaque(true);
        menuPanel.setBackground(new Color(250, 250, 250));
        menuPanel.setOnCloseCallback(() -> {
            toggleMenu(null);
        });
        getContentPane().add(menuPanel);
        getContentPane().setComponentZOrder(menuPanel, 0);
        revalidate();
        repaint();

        setLayout(null);
        setSize(1440, 1024);
        setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fondo = new javax.swing.JPanel();
        barra = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        Closebtn = new javax.swing.JPanel();
        Closetxt = new javax.swing.JLabel();
        minimizebtn = new javax.swing.JPanel();
        minimizetxt = new javax.swing.JLabel();
        Asunto = new componentes.IconTextField();
        MensajeTxt = new componentes.IconTextField();
        ButtonEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fondo.setBackground(new java.awt.Color(250, 250, 250));
        fondo.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        barra.setBackground(new java.awt.Color(30, 56, 136));
        barra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                barraMousePressed(evt);
            }
        });
        barra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                barraMouseDragged(evt);
            }
        });
        barra.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("FLEX-IA");
        barra.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleMenu(evt);
            }
        });
        barra.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 30));

        Closebtn.setBackground(new java.awt.Color(30, 56, 136));

        Closetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Closetxt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/cerrar.png"))); // NOI18N
        Closetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClosetxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ClosetxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                ClosetxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout ClosebtnLayout = new javax.swing.GroupLayout(Closebtn);
        Closebtn.setLayout(ClosebtnLayout);
        ClosebtnLayout.setHorizontalGroup(
                ClosebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ClosebtnLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(Closetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                        javax.swing.GroupLayout.PREFERRED_SIZE)));
        ClosebtnLayout.setVerticalGroup(
                ClosebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(Closetxt, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE));

        barra.add(Closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1380, 0, -1, 40));

        minimizebtn.setBackground(new java.awt.Color(30, 56, 136));

        minimizetxt.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        minimizetxt.setText("-");
        minimizetxt.setFont(FuenteUtil.cargarFuente("EpundaSlab-EXtrabold.ttf", 30f));
        minimizetxt.setForeground(new Color(250, 250, 250));
        minimizetxt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                minimizetxtMouseClicked(evt);
            }

            public void mouseEntered(java.awt.event.MouseEvent evt) {
                minimizetxtMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                minimizetxtMouseExited(evt);
            }
        });

        javax.swing.GroupLayout minimizebtnLayout = new javax.swing.GroupLayout(minimizebtn);
        minimizebtn.setLayout(minimizebtnLayout);
        minimizebtnLayout.setHorizontalGroup(
                minimizebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 60, Short.MAX_VALUE)
                        .addGroup(minimizebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(minimizebtnLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(minimizetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 60,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));
        minimizebtnLayout.setVerticalGroup(
                minimizebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 40, Short.MAX_VALUE)
                        .addGroup(minimizebtnLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(minimizebtnLayout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(minimizetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 40,
                                                javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))));

        barra.add(minimizebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1312, 0, 60, 40));

        fondo.add(barra, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 40));

        Asunto.setArc(10);
        Asunto.setText("Escriba aqui el asunto");
        Asunto.setToolTipText("");
        Asunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsuntoActionPerformed(evt);
            }
        });

        fondo.add(Asunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 365, 41));

        MensajeTxt.setArc(10);
        MensajeTxt.setText("Escriba aqui su mensaje");
        MensajeTxt.setToolTipText("");
        MensajeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MensajeTxtActionPerformed(evt);
            }
        });
        fondo.add(MensajeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 365, 224));

        ButtonEnviar.setBackground(new java.awt.Color(152, 206, 255));
        ButtonEnviar.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonEnviar.setText("Enviar");
        ButtonEnviar.setToolTipText("");
        ButtonEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonEnviarMouseEntered(evt);
            }

            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonEnviarMouseExited(evt);
            }
        });
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });
        fondo.add(ButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 830, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Contáctanos.png"))); // NOI18N
        fondo.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(fondo, javax.swing.GroupLayout.PREFERRED_SIZE,
                                javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEnviarMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ButtonEnviarMouseEntered
        ButtonEnviar.setBackground(new Color(0x1E3888));
        ButtonEnviar.setForeground(Color.WHITE);
    }// GEN-LAST:event_ButtonEnviarMouseEntered

    private void ButtonEnviarMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ButtonEnviarMouseExited
        ButtonEnviar.setBackground(new Color(0x98CEFF));
        ButtonEnviar.setForeground(Color.BLACK);
    }// GEN-LAST:event_ButtonEnviarMouseExited

    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {
        String asunto = Asunto.getText().trim();
        String mensaje = MensajeTxt.getText().trim();

        // Obtener correo del usuario desde la sesión
        String correoUsuario = SesionUsuario.getInstancia().getCorreoUsuario();

        if (correoUsuario == null || correoUsuario.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ No se pudo identificar el usuario. Por favor inicie sesión nuevamente.",
                    "Error de sesión",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validaciones
        if (asunto.isEmpty() || mensaje.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "⚠️ Por favor complete tanto el asunto como el mensaje",
                    "Campos incompletos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (asunto.equals("Escriba aqui el asunto") || mensaje.equals("Escriba aqui su mensaje")) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "⚠️ Por favor ingrese un asunto y mensaje válidos",
                    "Datos no válidos",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Correo de destino (tu empresa)
        String correoEmpresa = "alexandriabiblioteca611@gmail.com";

        // Mensaje HTML bien estructurado CON EL CORREO DEL USUARIO
        String htmlMensaje = "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;'>"
                + "<h2 style='color: #1E3888;'>Nuevo mensaje de contacto - FLEX-IA</h2>"
                + "<div style='background: #f5f5f5; padding: 15px; border-radius: 5px; margin: 10px 0;'>"
                + "<p><strong>📧 Correo del usuario:</strong> " + correoUsuario + "</p>"
                + "<p><strong>📋 Asunto:</strong> " + asunto + "</p>"
                + "</div>"
                + "<div style='background: #f9f9f9; padding: 15px; border-left: 4px solid #98CEFF; margin: 10px 0;'>"
                + "<p><strong>💬 Mensaje:</strong></p>"
                + "<p style='white-space: pre-line;'>" + mensaje.replace("\n", "<br>") + "</p>"
                + "</div>"
                + "<hr style='border: 1px solid #ddd;'>"
                + "<p style='color: #666; font-size: 12px;'>Este mensaje fue enviado desde el formulario de contacto de FLEX-IA</p>"
                + "</div>";

        // Enviar correo
        boolean enviado = enviarCorreoConReplyTo(correoEmpresa, "Contacto FLEX-IA: " + asunto, htmlMensaje,
                correoUsuario);

        if (enviado) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "✅ Mensaje enviado con éxito\nTe contactaremos pronto a: " + correoUsuario,
                    "Éxito",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);

            // Limpiar campos
            Asunto.setText("");
            MensajeTxt.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "❌ Error al enviar el mensaje\nPor favor intenta nuevamente",
                    "Error",
                    javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }


    private void MensajeTxtActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_MensajeTxtActionPerformed
        MensajeTxt.setText("");
    }// GEN-LAST:event_MensajeTxtActionPerformed

    private void AsuntoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_AsuntoActionPerformed
        Asunto.setText("");
    }// GEN-LAST:event_AsuntoActionPerformed

    private void barraMousePressed(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_barraMousePressed
        xmouse = evt.getX();
        ymouse = evt.getY();
    }// GEN-LAST:event_barraMousePressed

    private void barraMouseDragged(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_barraMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xmouse, y - ymouse);
    }// GEN-LAST:event_barraMouseDragged

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }// GEN-LAST:event_ExitMouseClicked

    private void ClosetxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ClosetxtMouseClicked
        System.exit(0);
    }// GEN-LAST:event_ClosetxtMouseClicked

    private void ClosetxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ClosetxtMouseEntered
        Closebtn.setBackground(Color.red);
        Closetxt.setForeground(new Color(250, 250, 250));
    }// GEN-LAST:event_ClosetxtMouseEntered

    private void ClosetxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_ClosetxtMouseExited
        Closebtn.setBackground(new Color(30, 56, 136));
        Closetxt.setForeground(new Color(250, 250, 250));
    }// GEN-LAST:event_ClosetxtMouseExited

    private void minimizetxtMouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_minimizetxtMouseClicked
        this.setState(JFrame.ICONIFIED);
    }// GEN-LAST:event_minimizetxtMouseClicked

    private void minimizetxtMouseEntered(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_minimizetxtMouseEntered
        minimizebtn.setBackground(Color.decode("#2e4ca9"));
    }// GEN-LAST:event_minimizetxtMouseEntered

    private void minimizetxtMouseExited(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_minimizetxtMouseExited
        minimizebtn.setBackground(new Color(30, 56, 136));
        minimizetxt.setForeground(new Color(250, 250, 250));
    }// GEN-LAST:event_minimizetxtMouseExited

    private void toggleMenu(java.awt.event.MouseEvent evt) {
        if (menuVisible) {
            // Ocultar menú
            Timer slideOut = new Timer(2, e -> {
                if (menuX > -menuWidth) {
                    menuX -= 10;
                    menuPanel.setLocation(menuX, 0);
                } else {
                    ((Timer) e.getSource()).stop();
                    menuVisible = false;
                }
            });
            slideOut.start();
        } else {
            // Mostrar menú
            Timer slideIn = new Timer(2, e -> {
                if (menuX < 0) {
                    menuX += 10;
                    menuPanel.setLocation(menuX, 0);
                } else {
                    ((Timer) e.getSource()).stop();
                    menuVisible = true;
                }
            });
            slideIn.start();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.IconTextField Asunto;
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JLabel Exit;
    private componentes.IconTextField MensajeTxt;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel fondo;
    private javax.swing.JPanel barra;
    private javax.swing.JPanel Closebtn;
    private javax.swing.JLabel Closetxt;
    private javax.swing.JPanel minimizebtn;
    private javax.swing.JLabel minimizetxt;
    // End of variables declaration//GEN-END:variables
}
