/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Color;
import javax.swing.Timer;
import static SignIn.CorreoService.enviarCorreoConReplyTo;

/**
 *
 * @author Karol
 */
public class Contactanos extends javax.swing.JFrame {

    private Menu menuPanel;
    private boolean menuVisible = false;
    private int menuWidth = 370; // ancho del panel del menú
    private int menuX = -menuWidth; // posición inicial fuera de pantalla
    private String correoUsuario;

    /**
     * Creates new form Contactanos
     */
    public Contactanos(String correoUsuario) {
        this.correoUsuario = correoUsuario;
        setUndecorated(true);
    
        initComponents();

        menuPanel = new Menu("Home");
        menuPanel.setBounds(menuX, 0, menuWidth, getHeight());
        menuPanel.setVisible(true);
        menuPanel.setOpaque(true);
        menuPanel.setBackground(new Color(250, 250, 250)); // fondo blanco visible

        getContentPane().add(menuPanel);
        getContentPane().setComponentZOrder(menuPanel, 0); // asegúrate que esté arriba
        revalidate();
        repaint();

        setLayout(null);
        // Configuración de la ventana
        setSize(1440, 1024);
        setLocationRelativeTo(null);
        setResizable(false); 

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Menu = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        Asunto = new componentes.IconTextField();
        MensajeTxt = new componentes.IconTextField();
        ButtonEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 56, 136));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("FLEX-IA");
        jPanel2.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        Menu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        Menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toggleMenu(evt);
            }
        });
        jPanel2.add(Menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 5, -1, 30));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        jPanel2.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 30, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 40));

        Asunto.setArc(10);
        Asunto.setText("Escriba aqui el asunto");
        Asunto.setToolTipText("");
        Asunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AsuntoActionPerformed(evt);
            }
        });

        jPanel1.add(Asunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 500, 365, 41));

        MensajeTxt.setArc(10);
        MensajeTxt.setText("Escriba aqui su mensaje");
        MensajeTxt.setToolTipText("");
        MensajeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MensajeTxtActionPerformed(evt);
            }
        });
        jPanel1.add(MensajeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 590, 365, 224));

        ButtonEnviar.setBackground(new java.awt.Color(152, 206, 255));
        ButtonEnviar.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonEnviar.setText("Enviar");
        ButtonEnviar.setToolTipText("");
        ButtonEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonEnviarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonEnviarMouseExited(evt);
            }
        });
        ButtonEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEnviarActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 830, 160, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Contáctanos.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonEnviarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEnviarMouseEntered
        ButtonEnviar.setBackground(new Color(0x1E3888));
        ButtonEnviar.setForeground(Color.WHITE);
    }//GEN-LAST:event_ButtonEnviarMouseEntered

    private void ButtonEnviarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEnviarMouseExited
        ButtonEnviar.setBackground(new Color(0x98CEFF));
        ButtonEnviar.setForeground(Color.BLACK);
    }//GEN-LAST:event_ButtonEnviarMouseExited

    private void ButtonEnviarActionPerformed(java.awt.event.ActionEvent evt) {                                           
        String asunto = Asunto.getText().trim();
        String mensaje = MensajeTxt.getText().trim();

        // Validaciones
        if (asunto.isEmpty() || mensaje.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "⚠️ Por favor complete tanto el asunto como el mensaje", 
                "Campos incompletos", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (asunto.equals("Escriba aqui el asunto") || mensaje.equals("Escriba aqui su mensaje")) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "⚠️ Por favor ingrese un asunto y mensaje válidos", 
                "Datos no válidos", 
                javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Correo de destino (tu empresa)
        String correoEmpresa = "alexandriabiblioteca611@gmail.com";

        // Mensaje HTML bien estructurado
        String htmlMensaje = "<div style='font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;'>"
                + "<h2 style='color: #1E3888;'>Nuevo mensaje de contacto - FLEX-IA</h2>"
                + "<div style='background: #f5f5f5; padding: 15px; border-radius: 5px; margin: 10px 0;'>"
                + "<p><strong>📧 Correo del usuario:</strong> " + correoUsuario + "</p>"
                + "<p><strong>📋 Asunto:</strong> " + asunto + "</p>"
                + "</div>"
                + "<div style='background: #f9f9f9; padding: 15px; border-left: 4px solid #98CEFF; margin: 10px 0;'>"
                + "<p><strong>💬 Mensaje:</strong></p>"
                + "<p style='white-space: pre-line;'>" + mensaje.replace("\n", "<br>") + "</p>"
                + "</div>"
                + "<hr style='border: 1px solid #ddd;'>"
                + "<p style='color: #666; font-size: 12px;'>Este mensaje fue enviado desde el formulario de contacto de FLEX-IA</p>"
                + "</div>";

        // Enviar correo
        boolean enviado = enviarCorreoConReplyTo(correoEmpresa, "Contacto FLEX-IA: " + asunto, htmlMensaje, correoUsuario);

        if (enviado) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "✅ Mensaje enviado con éxito\nTe contactaremos pronto", 
                "Éxito", 
                javax.swing.JOptionPane.INFORMATION_MESSAGE);
            
            // Limpiar campos
            Asunto.setText("");
            MensajeTxt.setText("");
        } else {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "❌ Error al enviar el mensaje\nPor favor intenta nuevamente", 
                "Error", 
                javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }

    private void MensajeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MensajeTxtActionPerformed
        MensajeTxt.setText("");
    }//GEN-LAST:event_MensajeTxtActionPerformed

    private void AsuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AsuntoActionPerformed
        Asunto.setText("");
    }//GEN-LAST:event_AsuntoActionPerformed

    private void toggleMenu(java.awt.event.MouseEvent evt) {
        if (menuVisible) {
            // Ocultar menú
            Timer slideOut = new Timer(2, e -> {
                if (menuX > -menuWidth) {
                    menuX -= 10;
                    menuPanel.setLocation(menuX, 0);
                } else {
                    ((Timer) e.getSource()).stop();
                    menuVisible = false;
                }
            });
            slideOut.start();
        } else {
            // Mostrar menú
            Timer slideIn = new Timer(2, e -> {
                if (menuX < 0) {
                    menuX += 10;
                    menuPanel.setLocation(menuX, 0);
                } else {
                    ((Timer) e.getSource()).stop();
                    menuVisible = true;
                }
            });
            slideIn.start();
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private componentes.IconTextField Asunto;
    private javax.swing.JButton ButtonEnviar;
    private javax.swing.JLabel Exit;
    private componentes.IconTextField MensajeTxt;
    private javax.swing.JLabel Menu;
    private javax.swing.JLabel Titulo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
