/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author Karol
 */
public class Ejercicio extends javax.swing.JFrame {

    /**
     * Creates new form Ejercicio
     */
    public Ejercicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        Titulo1 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JLabel();
        ButtonSiguiente = new javax.swing.JButton();
        ButtonAnterior = new javax.swing.JButton();
        roundedPanel1 = new Rounded.RoundedPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(30, 56, 136));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo1.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 24)); // NOI18N
        Titulo1.setForeground(new java.awt.Color(255, 255, 255));
        Titulo1.setText("FLEX-IA");
        jPanel3.add(Titulo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, 40));

        Exit1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        Exit1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Exit1MouseClicked(evt);
            }
        });
        jPanel3.add(Exit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 0, 30, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 905, 40));

        ButtonSiguiente.setBackground(new java.awt.Color(152, 206, 255));
        ButtonSiguiente.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonSiguiente.setText("Siguiente");
        ButtonSiguiente.setToolTipText("");
        ButtonSiguiente.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonSiguiente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonSiguienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonSiguienteMouseExited(evt);
            }
        });
        ButtonSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonSiguienteActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 610, 120, 40));

        ButtonAnterior.setBackground(new java.awt.Color(152, 206, 255));
        ButtonAnterior.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonAnterior.setText("Anterior");
        ButtonAnterior.setToolTipText("");
        ButtonAnterior.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonAnterior.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonAnteriorMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonAnteriorMouseExited(evt);
            }
        });
        ButtonAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonAnteriorActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonAnterior, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 610, 120, 40));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
        );

        jPanel1.add(roundedPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 500, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 680, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Exit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Exit1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Exit1MouseClicked

    private void ButtonSiguienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSiguienteMouseEntered
        ButtonSiguiente.setBackground(new Color(0x1E3888));
        ButtonSiguiente.setForeground(Color.WHITE);
    }//GEN-LAST:event_ButtonSiguienteMouseEntered

    private void ButtonSiguienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonSiguienteMouseExited
        ButtonSiguiente.setBackground(new Color(0x98CEFF));
        ButtonSiguiente.setForeground(Color.BLACK);
    }//GEN-LAST:event_ButtonSiguienteMouseExited

    private void ButtonSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonSiguienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonSiguienteActionPerformed

    private void ButtonAnteriorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAnteriorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAnteriorMouseEntered

    private void ButtonAnteriorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonAnteriorMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAnteriorMouseExited

    private void ButtonAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonAnteriorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ejercicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ejercicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonAnterior;
    private javax.swing.JButton ButtonSiguiente;
    private javax.swing.JLabel Exit1;
    private javax.swing.JLabel Titulo1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private Rounded.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
