package Interfaz;

import java.awt.Color;

/**
 *
 * @author Karol
 */
public class Instrucciones extends javax.swing.JFrame {

    /**
     * Creates new form Instrucciones
     */
    public Instrucciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        Titulo = new javax.swing.JLabel();
        Exit = new javax.swing.JLabel();
        ButtonVolver = new javax.swing.JButton();
        ButtonEjercicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(250, 250, 250));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(30, 56, 136));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Titulo.setFont(new java.awt.Font("Epunda Slab ExtraBold", 0, 24)); // NOI18N
        Titulo.setForeground(new java.awt.Color(255, 255, 255));
        Titulo.setText("FLEX-IA");
        jPanel2.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 0, -1, 40));

        Exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/exit.png"))); // NOI18N
        Exit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitMouseClicked(evt);
            }
        });
        jPanel2.add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1410, 0, 30, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1440, 40));

        ButtonVolver.setBackground(new java.awt.Color(217, 217, 217));
        ButtonVolver.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonVolver.setForeground(new java.awt.Color(30, 56, 136));
        ButtonVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/arrow-back.png"))); // NOI18N
        ButtonVolver.setText("Volver");
        ButtonVolver.setToolTipText("");
        ButtonVolver.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonVolver.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonVolverMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonVolverMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonVolverMouseExited(evt);
            }
        });
        ButtonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonVolverActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 840, 150, 40));

        ButtonEjercicio.setBackground(new java.awt.Color(30, 56, 136));
        ButtonEjercicio.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonEjercicio.setForeground(new java.awt.Color(250, 250, 250));
        ButtonEjercicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/photo-camera.png"))); // NOI18N
        ButtonEjercicio.setText("Hacer Ejercicio");
        ButtonEjercicio.setToolTipText("");
        ButtonEjercicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonEjercicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonEjercicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonEjercicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonEjercicioMouseExited(evt);
            }
        });
        ButtonEjercicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonEjercicioActionPerformed(evt);
            }
        });
        jPanel1.add(ButtonEjercicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(755, 840, 200, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1440, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1024, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonVolverMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVolverMouseEntered
        ButtonVolver.setBackground(new Color(0x1E3888));
        ButtonVolver.setForeground(Color.WHITE);
    }//GEN-LAST:event_ButtonVolverMouseEntered

    private void ButtonVolverMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVolverMouseExited
        ButtonVolver.setBackground(new Color(0xD9D9D9));
        ButtonVolver.setForeground(new Color(0x1E3888));
    }//GEN-LAST:event_ButtonVolverMouseExited

    private void ButtonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonVolverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonVolverActionPerformed

    private void ButtonEjercicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEjercicioMouseEntered
        ButtonEjercicio.setBackground(new Color(0xD9D9D9));
        ButtonEjercicio.setForeground(new Color(0x1E3888));
    }//GEN-LAST:event_ButtonEjercicioMouseEntered

    private void ButtonEjercicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEjercicioMouseExited
        ButtonEjercicio.setBackground(new Color(0x1E3888));
        ButtonEjercicio.setForeground(Color.WHITE);
    }//GEN-LAST:event_ButtonEjercicioMouseExited

    private void ButtonEjercicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonEjercicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonEjercicioActionPerformed

    private void ButtonVolverMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonVolverMouseClicked
        // Cerrar la ventana actual
        this.dispose();

        // Abrir la ventana de LogIn
        Ejercicios Ejercicios = new Ejercicios();
        Ejercicios.setVisible(true);
        Ejercicios.setLocationRelativeTo(null); // Centrar en pantalla
    }//GEN-LAST:event_ButtonVolverMouseClicked

    private void ButtonEjercicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonEjercicioMouseClicked
        // Abrir la ventana de LogIn
        Ejercicio Ejercicio = new Ejercicio();
        Ejercicio.setVisible(true);
        Ejercicio.setLocationRelativeTo(null); // Centrar en pantalla
    }//GEN-LAST:event_ButtonEjercicioMouseClicked

    private void ExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Instrucciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Instrucciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonEjercicio;
    private javax.swing.JButton ButtonVolver;
    private javax.swing.JLabel Exit;
    private javax.swing.JLabel Titulo;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
