/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interfaz;

import java.awt.Color;

/**
 *
 * @author Karol
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundedPanel1 = new Rounded.RoundedPanel();
        ButtonCerrarSesion = new javax.swing.JButton();
        Bienvenido = new javax.swing.JLabel();
        FotoPerfil = new javax.swing.JLabel();
        Close = new javax.swing.JLabel();
        Inicio = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        Videos = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        Estadisticas = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        Perfil = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        Contactanos = new javax.swing.JButton();
        jSeparator5 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        roundedPanel1.setBackground(new java.awt.Color(250, 250, 250));
        roundedPanel1.setLeftRounded(false);

        ButtonCerrarSesion.setBackground(new java.awt.Color(30, 56, 136));
        ButtonCerrarSesion.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        ButtonCerrarSesion.setForeground(new java.awt.Color(250, 250, 250));
        ButtonCerrarSesion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/log-out.png"))); // NOI18N
        ButtonCerrarSesion.setText("Cerrar Sesión");
        ButtonCerrarSesion.setToolTipText("");
        ButtonCerrarSesion.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ButtonCerrarSesion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonCerrarSesionMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ButtonCerrarSesionMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ButtonCerrarSesionMouseExited(evt);
            }
        });
        ButtonCerrarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCerrarSesionActionPerformed(evt);
            }
        });

        Bienvenido.setFont(new java.awt.Font("Epunda Slab Medium", 0, 32)); // NOI18N
        Bienvenido.setText("Bienvenid@ User!");

        FotoPerfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 5.png"))); // NOI18N

        Close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/BlueExit.png"))); // NOI18N
        Close.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CloseMouseClicked(evt);
            }
        });

        Inicio.setBackground(new java.awt.Color(250, 250, 250));
        Inicio.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Inicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Home.png"))); // NOI18N
        Inicio.setText("Inicio");
        Inicio.setToolTipText("");
        Inicio.setBorderPainted(false);
        Inicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Inicio.setFocusPainted(false);
        Inicio.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Inicio.setIconTextGap(20);
        Inicio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                InicioMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InicioMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InicioMouseExited(evt);
            }
        });
        Inicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InicioActionPerformed(evt);
            }
        });

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));

        Videos.setBackground(new java.awt.Color(250, 250, 250));
        Videos.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Videos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Video.png"))); // NOI18N
        Videos.setText("Videos");
        Videos.setToolTipText("");
        Videos.setAlignmentX(0.5F);
        Videos.setBorderPainted(false);
        Videos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Videos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Videos.setIconTextGap(20);
        Videos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                VideosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                VideosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                VideosMouseExited(evt);
            }
        });
        Videos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VideosActionPerformed(evt);
            }
        });

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));

        Estadisticas.setBackground(new java.awt.Color(250, 250, 250));
        Estadisticas.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Estadisticas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Stats.png"))); // NOI18N
        Estadisticas.setText("Estadísticas");
        Estadisticas.setToolTipText("");
        Estadisticas.setAlignmentX(0.5F);
        Estadisticas.setBorderPainted(false);
        Estadisticas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Estadisticas.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Estadisticas.setIconTextGap(20);
        Estadisticas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EstadisticasMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                EstadisticasMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EstadisticasMouseExited(evt);
            }
        });
        Estadisticas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EstadisticasActionPerformed(evt);
            }
        });

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));

        Perfil.setBackground(new java.awt.Color(250, 250, 250));
        Perfil.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Perfil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/user_1.png"))); // NOI18N
        Perfil.setText("Mi cuenta");
        Perfil.setToolTipText("");
        Perfil.setAlignmentX(0.5F);
        Perfil.setBorderPainted(false);
        Perfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Perfil.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Perfil.setIconTextGap(20);
        Perfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                PerfilMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                PerfilMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                PerfilMouseExited(evt);
            }
        });
        Perfil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerfilActionPerformed(evt);
            }
        });

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));

        Contactanos.setBackground(new java.awt.Color(250, 250, 250));
        Contactanos.setFont(new java.awt.Font("Epunda Slab", 0, 20)); // NOI18N
        Contactanos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Email.png"))); // NOI18N
        Contactanos.setText("Contáctanos");
        Contactanos.setToolTipText("");
        Contactanos.setAlignmentX(0.5F);
        Contactanos.setBorderPainted(false);
        Contactanos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Contactanos.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        Contactanos.setIconTextGap(20);
        Contactanos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ContactanosMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ContactanosMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ContactanosMouseExited(evt);
            }
        });
        Contactanos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContactanosActionPerformed(evt);
            }
        });

        jSeparator5.setForeground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout roundedPanel1Layout = new javax.swing.GroupLayout(roundedPanel1);
        roundedPanel1.setLayout(roundedPanel1Layout);
        roundedPanel1Layout.setHorizontalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                        .addComponent(Close)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                        .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jSeparator1)
                            .addComponent(Inicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Videos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Estadisticas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Perfil, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator4)
                            .addComponent(Contactanos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(93, 93, 93))))
            .addGroup(roundedPanel1Layout.createSequentialGroup()
                .addGroup(roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addComponent(Bienvenido))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(107, 107, 107)
                        .addComponent(ButtonCerrarSesion))
                    .addGroup(roundedPanel1Layout.createSequentialGroup()
                        .addGap(129, 129, 129)
                        .addComponent(FotoPerfil)))
                .addContainerGap(82, Short.MAX_VALUE))
        );
        roundedPanel1Layout.setVerticalGroup(
            roundedPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, roundedPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(Close)
                .addGap(120, 120, 120)
                .addComponent(FotoPerfil)
                .addGap(33, 33, 33)
                .addComponent(Bienvenido)
                .addGap(40, 40, 40)
                .addComponent(Inicio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Videos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Estadisticas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Perfil)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Contactanos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(ButtonCerrarSesion)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(roundedPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonCerrarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCerrarSesionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ButtonCerrarSesionActionPerformed

    private void ButtonCerrarSesionMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCerrarSesionMouseExited
        ButtonCerrarSesion.setBackground(new Color(0x1E3888));
        ButtonCerrarSesion.setForeground(Color.WHITE);
    }//GEN-LAST:event_ButtonCerrarSesionMouseExited

    private void ButtonCerrarSesionMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCerrarSesionMouseEntered
        ButtonCerrarSesion.setBackground(new Color(0xD9D9D9));
        ButtonCerrarSesion.setForeground(new Color(0x1E3888));
    }//GEN-LAST:event_ButtonCerrarSesionMouseEntered

    private void ButtonCerrarSesionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonCerrarSesionMouseClicked
        // Abrir la ventana de LogIn
        Ejercicio Ejercicio = new Ejercicio();
        Ejercicio.setVisible(true);
        Ejercicio.setLocationRelativeTo(null); // Centrar en pantalla
    }//GEN-LAST:event_ButtonCerrarSesionMouseClicked

    private void InicioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseClicked
        // Abrir la ventana de LogIn
        Home Home = new Home();
        Home.setVisible(true);
        Home.setLocationRelativeTo(null); // Centrar en pantalla
    }//GEN-LAST:event_InicioMouseClicked

    private void InicioMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseEntered
        Inicio.setBackground(new Color(0x98CEFF));
        Inicio.setForeground(Color.BLACK);
    }//GEN-LAST:event_InicioMouseEntered

    private void InicioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InicioMouseExited
        Inicio.setBackground(new Color(0xFAFAFA));
        Inicio.setForeground(Color.BLACK);
    }//GEN-LAST:event_InicioMouseExited

    private void InicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InicioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InicioActionPerformed

    private void VideosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VideosMouseClicked
        // Abrir la ventana de LogIn
        Ejercicios Ejercicios = new Ejercicios();
        Ejercicios.setVisible(true);
        Ejercicios.setLocationRelativeTo(null); // Centrar en pantalla
    }//GEN-LAST:event_VideosMouseClicked

    private void VideosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VideosMouseEntered
        Videos.setBackground(new Color(0x98CEFF));
        Videos.setForeground(Color.BLACK);
    }//GEN-LAST:event_VideosMouseEntered

    private void VideosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_VideosMouseExited
        Videos.setBackground(new Color(0xFAFAFA));
        Videos.setForeground(Color.BLACK);
    }//GEN-LAST:event_VideosMouseExited

    private void VideosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VideosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VideosActionPerformed

    private void CloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_CloseMouseClicked

    private void EstadisticasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasMouseClicked
        
    }//GEN-LAST:event_EstadisticasMouseClicked

    private void EstadisticasMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadisticasMouseEntered

    private void EstadisticasMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EstadisticasMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadisticasMouseExited

    private void EstadisticasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EstadisticasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EstadisticasActionPerformed

    private void PerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseClicked
        // Abrir la ventana de LogIn
        Perfil Perfil = new Perfil();
        Perfil.setVisible(true);
        Perfil.setLocationRelativeTo(null); // Centrar en pantalla
    }//GEN-LAST:event_PerfilMouseClicked

    private void PerfilMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseEntered
        Perfil.setBackground(new Color(0x98CEFF));
        Perfil.setForeground(Color.BLACK);
    }//GEN-LAST:event_PerfilMouseEntered

    private void PerfilMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_PerfilMouseExited
        Perfil.setBackground(new Color(0xFAFAFA));
        Perfil.setForeground(Color.BLACK);
    }//GEN-LAST:event_PerfilMouseExited

    private void PerfilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerfilActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PerfilActionPerformed

    private void ContactanosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactanosMouseClicked
        // Abrir la ventana de LogIn
        Contactanos Contactanos = new Contactanos();
        Contactanos.setVisible(true);
        Contactanos.setLocationRelativeTo(null); // Centrar en pantalla
    }//GEN-LAST:event_ContactanosMouseClicked

    private void ContactanosMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactanosMouseEntered
        Contactanos.setBackground(new Color(0x98CEFF));
        Contactanos.setForeground(Color.BLACK);
    }//GEN-LAST:event_ContactanosMouseEntered

    private void ContactanosMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ContactanosMouseExited
        Contactanos.setBackground(new Color(0xFAFAFA));
        Contactanos.setForeground(Color.BLACK);
    }//GEN-LAST:event_ContactanosMouseExited

    private void ContactanosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContactanosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContactanosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JButton ButtonCerrarSesion;
    private javax.swing.JLabel Close;
    private javax.swing.JButton Contactanos;
    private javax.swing.JButton Estadisticas;
    private javax.swing.JLabel FotoPerfil;
    private javax.swing.JButton Inicio;
    private javax.swing.JButton Perfil;
    private javax.swing.JButton Videos;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private Rounded.RoundedPanel roundedPanel1;
    // End of variables declaration//GEN-END:variables
}
